---
title: "How to Contribute"
draft: false
menu:
  docs:
    title:
    parent: "Introduction"
    identifier: "Introduction/How_to_contribute"
    weight: 
---

The following article contains a selection of common ways to contribute to the community projects.

== Reporting issues

Reporting issues is a great way to contribute (if done correctly). The software projects are using bug trackers to keep track of bugs and to link patches or changes with these bug reports.

See the article link:/documentation/Introduction/Where_to_report_bugs[where to report bugs] to find out where you can report bugs.

== Contributing code

By contributing code, for example as documented in the following project pages (alphabetical order):

* elementary: https://elementary.io/get-involved[Get Involved] and the https://github.com/orgs/elementary/projects/108[ARM project on GitHub]
* KDE: see https://community.kde.org/Get_Involved[Get Involved] and https://community.kde.org/Help:Contribute[Help:Contribute]
* Plasma Mobile: https://plasma-mobile.org/get-source/ (see the "Contributing" section)

== Donating to community projects and developers

Many community projects and developers are working on the software on their free time. Donating to community projects and developers is a great way to support these projects and developers developing the software for the devices. The following list is an exemplary selection to which projects and developers can be donated to (in alphabetical order):

TIP: The following list is not a comprehensive list and solely a selection of different community projects and developers, which can be supported. Any FOSS development effort is valuable and should be rewarded, please support your favorite developer(s) or project(s) even if not mentioned on the list Your name or project not on the list? 

=== Community projects

* Armbian: https://www.armbian.com/donate/
* elementary: https://elementary.io/get-involved
* KDE: https://kde.org/community/donations/
* LibreELEC: https://libreelec.tv/sponsor/
* Manjaro ARM: https://opencollective.com/manjaro-arm/donate[Open Collective], https://en.liberapay.com/Manjaro-ARM/[Liberapay], https://www.patreon.com/manjaroarm[Patreon] (see https://manjaro.org/donate/ for an overview)
* Mobian: https://liberapay.com/mobian/donate[Liberapay]
* postmarketOS: https://postmarketos.org/donate/
* UBports: https://ubports.com/donate

and many more!

=== Developers

* Danct12: https://ko-fi.com/danct12[Ko-fi], https://liberapay.com/Danct12[Liberapay], https://patreon.com/Danct12[Patreon]
* megi: https://xnux.eu/contribute.html#toc-donations

and many more!

== Help with the documentation

All projects typically require help with the documentation. That can include the wikis of the projects, help pages, tutorials, manuals and technical or informative drawings.

== Other ways to contribute

Other ways to contribute to the projects might include:

* Translations and localization
* Designs and creative work
* Ideas
* Supplying hardware

and many more!

== By being a positive member of the community

By being a positive member of the community you can help answering common questions and help people find the correct places for their inquiries.