---
title: "Bootloaders"
draft: false
menu:
  docs:
    title:
    parent: "PinePhone_Pro/Software"
    identifier: "PinePhone_Pro/Software/Bootloaders"
    weight: 2
---

The following section contains notes regarding compatible bootloaders with the PinePhone Pro.

== rk2aw

The rk2aw pre-loader program is designed for modern Rockchip SoCs. It modifies the boot ROM bootloader load order from the original and rigid “SPI NOR flash -> eMMC -> SD card” to a more flexible “SD card -> eMMC -> SPI NOR flash”. Additionally, it enables robust A/B bootloader updates in SPI NOR flash, allowing users to choose fallback options via a pre-boot menu. It also exposes both eMMC and microSD card as USB devices. For details see the https://xnux.eu/rk2aw/[rk2aw page].

PinePhone Pro models ordered after November 2023 are shipped with rk2aw pre-installed. Otherwise, follow the instructions in this section to install it.

=== Install rk2aw

Make sure the phone’s SSH server is up and running on the PinePhone Pro's stock operating system. Then Connect to your phone from your Linux computer using SSH:

[source,console]
----
$ ssh USER@PHONEIP
$ mkdir -p ~/rk2aw
$ cd ~/rk2aw
$ curl -O https://xff.cz/kernels/bootloaders-2024.04/ppp.tar.gz
$ tar -xvzf ppp.tar.gz -C ~/rk2aw
$ cd ~/rk2aw/ppp
$ sudo ./spinor-flash-initial-setup.sh
----

Further instructions can be found on the link:https://xff.cz/kernels/bootloaders-2024.04/ppp/rk2aw/INSTALL[author's website].


== U-Boot

U-Boot is an open-source bootloader commonly used in embedded operating systems and is often pre-installed on device images.

=== Install U-Boot

In case you need to install or re-install it, follow these steps.

Download the U-Boot build (the source code of the build can be on link:https://xff.cz/git/u-boot/tree/?h=ppp-2023.07[xff.cz]):

[source,console]
----
$ mkdir -p ~/rk2aw
$ cd ~/rk2aw
$ curl -O https://xff.cz/kernels/bootloaders-2024.04/ppp.tar.gz
$ tar -xzf ppp.tar.gz
----

Then write the U-Boot image to the device using the following command, where device can be found under _lsblk_ command:

[source,console]
----
$ sudo dd if=~/rk2aw/ppp/foss/u-boot-rockchip.bin of=/dev/[DEVICE] bs=512 seek=64 status=progress conv=fsync
----

If you are interested in building this U-Boot image yourself, you will need to copy the `~/rk2aw/ppp/foss/.config` file from the archive above to the root of your U-Boot source directory.

== Tow-Boot

_Tow-Boot_ is an opinionated distribution of _U-Boot_ and brings numerous advantages over stock _U-Boot_, such as the possibility to choose from booting the eMMC or microSD card using the volume buttons during boot, as well as a _USB Mass Storage mode_, where the device can be written to by connecting the device to a computer via USB.

The user can flash Tow-Boot to the PinePhone Pro using the https://tow-boot.org/devices/pine64-pinephonePro.html[instructions on the Tow-Boot website].

== levinboot

The levinboot bootloader is another option for the PinePhone Pro. The project repository can be found https://gitlab.com/DeltaGem/levinboot/-/tree/master/[here]. (Pinephone Pro supporting fork is https://xff.cz/git/levinboot/[here].)