---
title: "Multi-distribution image"
draft: false
menu:
  docs:
    title:
    parent: "PinePhone_Pro/Software"
    identifier: "PinePhone_Pro/Various/Multi-distribution_image"
    weight:
---

Rk2aw pre-loader program can change apparent boot ROM bootloader load order from original and inflexible "SPI NOR flash -> eMMC -> SD card" to "SD card -> eMMC -> SPI NOR flash" and to implement robust, seamless A/B bootloader updates in SPI NOR flash with user selectable fallback (via a pre-boot menu). Since 2024feb15 version also SDcard, like eMMC, is exposed to USB and can be mounted as device. This can save wearing of the SD slot and of the backcover under heavy testing condition of different distributions. Further instructions regarding rk2aw can be found on link:https://xff.cz/kernels/bootloaders-2024.04/ppp/rk2aw/INSTALL[megi's website]. Please note that pre-loader and userspace utility to flash it are free, but not open-source.

This article explains how to install megi's rk2aw pre-loader, U-Boot to SPI and a multi-distribution image to the microSD card.

== Flash rk2Aw pre-loader to SPI

Connect PinePhone Pro to a Linux machine (USB cable or wifi connection is fine). Make sure phone's ssh server is up and running, and find the target IP address. Start a ssh connection from PC and download from the web the pre-loader installer to flash into the phone's SPI.

 sudo systemctl enable --now sshd # on phone's terminal window
 ip address # on phone's terminal window

 mkdir -p ~/ppp # on pc's terminal window from now on
 cd ~/ppp
 ssh <user>@<phoneip>
 curl -O https://xff.cz/kernels/bootloaders-2024.04/ppp.tar.gz
 tar -xvzf ppp.tar.gz -C ~/ppp
 # scp -r ~/ppp <user>@<phoneip>:~/Downloads # as option when direct download is not possible
 sudo ./spinor-flash-initial-setup.sh

== Build multi-distro on the microSD card

If your microSD card in not empty, first get rid of any left signature. Use GParted GUI to format `cleared` each partition, than remove all partitions. Next open terminal window an wipe the content.

 sudo wipefs /dev/sdb # shows current signatures
 sudo wipefs --all --force /dev/sdb # erase current signatures

Zero-write the microSD card

 sudo dd if=/dev/zero of=/dev/sdb status=progress bs=32768 count=1 # quick way erasing
 sudo dd if=/dev/zero of=/dev/sdb status=progress bs=32768 count=945728 # 32 GB
 sudo dd if=/dev/zero of=/dev/sdb status=progress bs=32768 count=1908880 # 64 GB
 sudo dd if=/dev/zero of=/dev/sdb status=progress bs=32768 count=3872000 # 128 GB

=== Partition the microSD card
Note: A minimum capacity of 64 GB for the microSD card is recommended for 5 distributions.

 sudo sfdisk /dev/sdb --wipe always <<EOF
  label: gpt
  first-lba: 64
  table-length: 8
  attrs=RequiredPartition, type=D7B1F817-AA75-2F4F-830D-84818A145370, start=64, size=32704, name="loader"
  attrs="RequiredPartition,LegacyBIOSBootable", size=11G, name="ALARM"
  attrs="RequiredPartition,LegacyBIOSBootable", size=11G, name="MANJARO"
  attrs="RequiredPartition,LegacyBIOSBootable", size=11G, name="MOBIAN"
  attrs="RequiredPartition,LegacyBIOSBootable", size=11G, name="PMOS"
  attrs="RequiredPartition,LegacyBIOSBootable", size=11G, name="UT"
  attrs="RequiredPartition,LegacyBIOSBootable", size=+, name="extra"
 EOF

Expected result

 Checking that no-one is using this disk right now ... OK
 Disk /dev/sdb: 58.25 GiB, 62550179840 bytes, 122168320 sectors
 Disk model: SD Card Reader  
 Units: sectors of 1 * 512 = 512 bytes
 Sector size (logical/physical): 512 bytes / 512 bytes
 I/O size (minimum/optimal): 512 bytes / 512 bytes
 >>> Script header accepted.
 New situation:
 Disklabel type: gpt
 Disk identifier: F71BFBA6-D2C3-4C20-8079-1401B10C724C
  Device    Start       End  Sectors   Size Type
  sdb1         64     32767    32704   16M  unknown
  sdb2      32768  23101439 23068672   11G  Linux fs
  sdb3   23101440  46170111 23068672   11G  Linux fs
  sdb4   46170112  69238783 23068672   11G  Linux fs
  sdb5   69238784  92307455 23068672   11G  Linux fs
  sdb6   92307456 115376127 23068672   11G  Linux fs
  sdb7  115376128 122167295  6791168  3.2G  Linux fs
 The partition table has been altered.
 Calling ioctl() to re-read partition table.
 Syncing disks.

=== Build Arch Linux partition

Download, decompress and mount the image. Copy rootfs and bootfs to the partition. Edit/replace some files.

 cd ~/ppp/distros
 wget https://github.com/dreemurrs-embedded/Pine64-Arch/releases/download/20230925/archlinux-pinephone-pro-phosh-20230925.img.xz
 xz -v -d -k archlinux-pinephone-pro-phosh-20230925.img.xz
 mv archlinux-pinephone-pro-phosh-20230925.img archlinux.img
 sudo losetup -P /dev/loop2 archlinux.img
 sudo mkdir /mnt/archlinux /mnt/archlinux/boot /mnt/archlinux/root /mnt/archlinuxsd
 sudo mount /dev/loop2p1 /mnt/archlinux/boot/
 sudo mount /dev/loop2p2 /mnt/archlinux/root/

 sudo dd if=/dev/loop2p2 of=/dev/sdb2 bs=1M status=progress conv=fsync
 sudo mount /dev/sdb2 /mnt/archlinuxsd/
 sudo scp -r /mnt/archlinux/boot/* /mnt/archlinuxsd/boot
 sudo mv /mnt/archlinuxsd/boot/boot.scr /mnt/archlinuxsd/boot/boot.scrORIG
 sudo mkdir /mnt/archlinuxsd/boot/extlinux
 sudo chmod a=rwx /mnt/archlinuxsd/boot/extlinux
 sudo chmod a=rwx /mnt/archlinuxsd/etc/fstab

 sudo tee /mnt/archlinuxsd/boot/extlinux/extlinux.conf <<EOF
  #/boot/extlinux/extlinux.conf
  menu title Pinephone Pro Boot Menu
  label l0
  menu label ALARM
  fdt /boot/dtbs/rockchip/rk3399-pinephone-pro.dtb
  kernel /boot/Image.gz
  initrd /boot/initramfs-linux.img
  append root=partlabel=ALARM console=ttyS2,115200 console=tty0 loglevel=7 rw rootwait
 EOF

 sudo tee /mnt/archlinuxsd/etc/fstab <<EOF
  #<file system>  <dir> <type> <options>   <dump> <pass>
  partlabel=ALARM /     ext4   rw,relatime 0      1
 EOF

=== Build Manjaro partition

Download, decompress and mount the image. Copy rootfs and bootfs to the partition. Edit/replace some files.

 cd ~/ppp/distros
 wget https://github.com/manjaro-pinephone/phosh/releases/download/beta37/Manjaro-ARM-phosh-pinephonepro-beta37.img.xz
 xz -v -d -k Manjaro-ARM-phosh-pinephonepro-beta37.img.xz
 mv Manjaro-ARM-phosh-pinephonepro-beta37.img manjaro.img
 sudo losetup -P /dev/loop3 manjaro.img
 sudo mkdir /mnt/manjaro /mnt/manjaro/boot /mnt/manjaro/root /mnt/manjarosd
 sudo mount /dev/loop3p1 /mnt/manjaro/boot/
 sudo mount /dev/loop3p2 /mnt/manjaro/root/

 sudo dd if=/dev/loop3p2 of=/dev/sdb3 bs=1M status=progress conv=fsync
 sudo mount /dev/sdb3 /mnt/manjarosd/
 sudo scp -r /mnt/manjaro/boot/* /mnt/manjarosd/boot
 sudo mv /mnt/manjarosd/boot/boot.scr /mnt/manjarosd/boot/boot.scrORIG
 sudo mkdir /mnt/manjarosd/boot/extlinux
 sudo chmod a=rwx /mnt/manjarosd/boot/extlinux
 sudo chmod a=rwx /mnt/manjarosd/etc/fstab

 sudo tee /mnt/manjarosd/boot/extlinux/extlinux.conf <<EOF
  #/boot/extlinux/extlinux.conf
  mwenu title Pinephone Pro Boot Menu
  label l0
  menu label MANJARO
  fdt /boot/dtbs/rockchip/rk3399-pinephone-pro.dtb
  kernel /boot/Image
  initrd /boot/initramfs-linux.img
  append root=partlabel=MANJARO console=ttyS2,115200 console=tty0 loglevel=7 rw rootwait
 EOF

 sudo tee /mnt/manjarosd/etc/fstab <<EOF
  #<file system>    <dir> <type> <options> <dump> <pass>
  partlabel=MANJARO /     ext4   defaults  0      1
 EOF

=== Build Mobian partition

Download, decompress and mount the image. Copy rootfs and bootfs to the partition. Edit/replace some files.

 cd ~/ppp/distros
 wget https://images.mobian.org/pinephonepro/weekly/mobian-pinephonepro-phosh-20240121.img.xz
 xz -v -d -k mobian-pinephonepro-phosh-20240121.img.xz
 mv mobian-pinephonepro-phosh-20240121.img mobian.img
 sudo losetup -P /dev/loop4 mobian.img
 sudo mkdir /mnt/mobian /mnt/mobian/boot /mnt/mobian/root /mnt/mobiansd
 sudo mount /dev/loop4p1 /mnt/mobian/boot/
 sudo mount /dev/loop4p2 /mnt/mobian/root/

 sudo dd if=/dev/loop4p2 of=/dev/sdb4 bs=1M status=progress conv=fsync
 sudo mount /dev/sdb4 /mnt/mobiansd/
 sudo scp -r /mnt/mobian/boot/* /mnt/mobiansd/boot
 sudo chmod a=rwx /mnt/mobiansd/boot/extlinux
 sudo chmod a=rwx /mnt/mobiansd/etc/fstab

 sudo nano /mnt/mobiansd/boot/extlinux/extlinux.conf # modify content as following
  ## /boot/extlinux/extlinux.conf file
  menu label MOBIAN
  linux /boot/vmlinuz-6.6-rockchip
  initrd /boot/initrd.img-6.6-rockchip
  fdtdir /boot/dtb-6.6-rockchip/
  append root=partlabel=MOBIAN console=ttyS2,115200 console=tty0 loglevel=7 rw rootwait
  #append root=UUID=b282b619-c9b7-4c15-9c3d-2005b35d5999 consoleblank=0 loglevel=7 ro quiet splash plymouth.ignore-serial>

 sudo tee /mnt/mobiansd/etc/fstab <<EOF
  #<file system>   <dir> <type> <options>                 <dump> <pass>
  partlabel=MOBIAN /     ext4   defaults,x-systemd.growfs	0      1
 EOF

To save and close terminal window digit: `Ctrl+X` to save, `Yes`, `Enter`.

=== Build PostmarketOS partition

Download, decompress and mount the image. Copy rootfs and bootfs to the partition. Edit/replace some files.
Optionally you can use bootstrap to generate distro image. Make sure you install pmbootstrap before building image.

 git clone --depth=1 https://git.sr.ht/~postmarketos/pmbootstrap
 mkdir -p ~/.local/bin
 ln -s "$PWD/pmbootstrap/pmbootstrap.py" ~/.local/bin/pmbootstrap
 source ~/.profile # remember to update your environment
 pmbootstrap --version # if this returns error see next command

 sudo tee -a ~/.profile <<EOF
  PATH="$HOME/.local/bin:$PATH"
 EOF

Start creating 2 GB empty image file, format and mount it.

 sudo su
 dd if=/dev/zero of=postmarketos.img bs=1 count=0 seek=2G status=progress && sync
 mkfs.ext4 postmarketos.img
 losetup -P /dev/loop0 postmarketos.img
 exit

Build PostmarketOS image via pmbootstrap

 pmbootstrap init # follow all the setup directions
 pmbootstrap status
 pmbootstrap pull
 pmbootstrap install --sdcard=/dev/loop0
 pmbootstrap shutdown # remember to deactivare chroot after the image creation

In you don't build PMOS image on your own, download, decompress and mount the image. Copy rootfs and bootfs to the partition. Edit/replace some files.

 cd ~/ppp/distros
 # wget https://images.postmarketos.org/bpo/v23.12/pine64-pinephonepro/phosh/20240214-0437/20240214-0437-postmarketOS-v23.12-phosh-22.3-pine64-pinephonepro.img.xz
 # xz -v -d -k 20240214-0437-postmarketOS-v23.12-phosh-22.3-pine64-pinephonepro.img.xz
 # mv 20240214-0437-postmarketOS-v23.12-phosh-22.3-pine64-pinephonepro.img postmarketos.img
 sudo losetup -P /dev/loop5 postmarketos.img
 sudo mkdir /mnt/postmarketos /mnt/postmarketos/boot /mnt/postmarketos/root /mnt/postmarketossd
 sudo mount /dev/loop5p1 /mnt/postmarketos/boot/
 sudo mount /dev/loop5p2 /mnt/postmarketos/root/

 sudo dd if=/dev/loop5p2 of=/dev/sdb5 bs=1M status=progress conv=fsync
 sudo mount /dev/sdb5 /mnt/postmarketossd/
 sudo scp -r /mnt/postmarketos/boot/* /mnt/postmarketossd/boot
 sudo mkdir /mnt/postmarketossd/boot/extlinux
 sudo chmod a=rwx /mnt/postmarketossd/boot/extlinux
 sudo chmod a=rwx /mnt/postmarketossd/etc/fstab

 sudo tee /mnt/postmarketossd/boot/extlinux/extlinux.conf <<EOF
  #/boot/extlinux/extlinux.conf
  default l0
  menu title U-Boot menu
  prompt 0
  timeout 10
  label l0
  menu label PMOS
  linux /boot/vmlinuz
  initrd /boot/initramfs-extra
  fdtdir /boot/dtbs-pine64-pinephonepro/
  append root=partlabel=PMOS console=ttyS2,115200 console=tty0 loglevel=7 rw rootwait
 EOF

 sudo tee /mnt/postmarketossd/etc/fstab <<EOF
  #<file system> <mount point> <type> <options> <dump> <pass>
  partlabel=PMOS /             ext4   defaults  0      0
 EOF

=== Build Ubuntu Touch partition

Download, decompress and mount the image. Copy rootfs and bootfs to the partition. Edit/replace some files.

 cd ~/ppp/distros
 wget https://ci.ubports.com/job/focal-hybris-rootfs-arm64/job/master/lastSuccessfulBuild/artifact/ubuntu-touch-pinephone-pro-img-arm64.raw.xz
 xz -v -d -k ubuntu-touch-pinephone-pro-img-arm64.raw.xz
 mv ubuntu-touch-pinephone-pro-img-arm64.raw ubuntu.raw
 sudo losetup -P /dev/loop6 ubuntu.raw
 sudo mkdir /mnt/ubuntutouch /mnt/ubuntutouch/boot /mnt/ubuntutouch/root /mnt/ubuntutouchsd
 sudo mount /dev/loop6p2 /mnt/ubuntutouch/boot/
 sudo mount /dev/loop6p3 /mnt/ubuntutouch/root/

 sudo dd if=/dev/loop6p3 of=/dev/sdb6 bs=1M status=progress conv=fsync
 sudo mount /dev/sdb6 /mnt/ubuntutouchsd/
 sudo scp -r /mnt/ubuntutouch/boot/* /mnt/ubuntutouchsd/boot
 sudo chmod a=rwx /mnt/ubuntutouchsd/etc/fstab
 sudo chmod a=rwx /mnt/ubuntutouchsd/boot/extlinux
 
 sudo nano /mnt/ubuntutouchsd/boot/extlinux/extlinux.conf # modify content as following
  ## /boot/extlinux/extlinux.conf file
  menu label UT
  linux /boot/vmlinuz-6.5.0-okpine-ut
  initrd /boot/initrd.img-6.5.0-okpine-ut
  fdtdir /boot/dtb-6.5.0-okpine-ut/rockchip/
  #append root=UUID=9f3cfee6-e7ed-4d4a-bfeb-e54ef502cec7 console=ttyS2,115200n8 consoleblank=0 loglevel=7 ro splash plymouth.ignore-serial-consoles vt.global_cursor_default=0
  append root=partlabel=UT console=ttyS2,115200 console=tty0 loglevel=7 rw rootwait

 sudo tee /mnt/ubuntutouchsd/etc/fstab <<EOF
  #<file system> <dir> <type> <options> <dump> <pass>
  partlabel=UT   /     ext4   defaults  0      1
 EOF

=== Unmount and detach all images

 sudo losetup -D
 sudo umount /mnt/*/*
 sudo umount /mnt/*
 sudo umount /media/*/*
 sudo umount /media/*
 sudo rm -r /mnt/*/*
 sudo rm -r /mnt/*
 sudo sudo rm -r /media/*/*
 sudo sudo rm -r /media/*
 
== Switching on device

According to megi's https://xnux.eu/rk2aw info, to operate your PinePhone Pro use power button and led feedback.

* Plug in USB power cord. Led blinks: 0.5s on, 0.5s off. Battery is slowly charging.
* Press shortly power button. Graphical menu appears, than just select the image to boot from.
* Press longer power button, led starts to blinks rapidly. Release power button, led blinks N times each second according to the selected image.

In example:

* Led blinks once each second and 1st image is selected;
* Led blinks twice each second and 2nd image is seleted;
* Led blinks triple each second and 3rd image is selected.
* Press shortly to move to next image.
* Press longer to boot the selected image.
* In case you hold the power button too long, the device is forced to power off.

== Troubleshooting

On first boot, if it doesn't happen automatically, you can manually resize each image to fill his entire partition using GParted GUI software or running `sudo resize2fs` into terminal window.

Any time a distribution update rebuilds the initramfs it is necessary to delete `/boot/boot.scr` again to keep the rk2aw menu clean.

In case you want to reinstall only one distribution, the easy way is to delete and recreate requested partition using GParted GUI.

If device doesn't start, connect a compatible link:https://pine64.com/product/pinebook-pinephone-pinetab-serial-console[serial cable] to headphone jack, switch off microswitch 6 and start a serial console to further investigate.

 ls /dev/ttyUSB* # check usb device from linux machine
 minicom -b 1500000 -D /dev/ttyUSB0
