---
title: "Multi-distribution image"
draft: false
menu:
  docs:
    title:
    parent: "PinePhone_Pro/Software"
    identifier: "PinePhone_Pro/Software/Multi-distribution_image"
    weight: 5
---

:toc:

This article explains how to install a multiple linux distribution enviroment on your PinePhone Pro. According to the flashed device you will be able to boot from the eMMC internal memory or from a microSD card.

== Pre-requisite rk2aw

Make sure your phone has the link:/documentation/PinePhone_Pro/Software/Bootloaders/#install_rk2aw[rk2aw pre-loader] installed to SPI flash.

== Setting variables

During processes of partitioning target device or building the image, make sure the needed variables are properly defined:

[TIP]
====
_DEVICE_ is the device name from the lsblk command +
_DISTROURL_ is the image downloading URL address of Linux distribution +
_MENUNAME_ is the name of graphical boot menu item +
_PARTNAME_ is the name of partition/distribution +
_PARTNUMBER_ is the number of partition/distribution +
_PARTSIZE_ is the GiB capacity of each partition +
_WORKDIR_ is the working directory path on your computer +
====

Each time you open a new terminal window, the values of the variables must be adapted, for example:

[source,shell]
----
DEVICE=sdb
DISTROURL=https://github.com/dreemurrs-embedded/Pine64-Arch/releases/download/20240308/archlinux-pinephone-pro-phosh-20240308.img.xz
MENUNAME=ARCH
PARTNAME=ppp-multi-image-${MENUNAME,,}
PARTNUMBER=2
PARTSIZE=11GiB
WORKDIR=~/ppp
----

This guide has been tested with following images:

* https://github.com/dreemurrs-embedded/Pine64-Arch/releases/download/20240308/archlinux-pinephone-pro-phosh-20240308.img.xz
* https://github.com/manjaro-pinephone/phosh/releases/download/beta37/Manjaro-ARM-phosh-pinephonepro-beta37.img.xz
* https://images.mobian.org/pinephonepro/weekly/mobian-rockchip-phosh-20240310.img.xz
* https://images.postmarketos.org/bpo/v23.12/pine64-pinephonepro/phosh/20240306-0437/20240306-0437-postmarketOS-v23.12-phosh-22.3-pine64-pinephonepro.img.xz
* https://gitlab.com/sailfishos-porters-ci/dont_be_evil-ci/-/jobs/artifacts/master/download?job=pinephonepro-rootfs

== Building

Connect your PinePhone Pro to a Linux computer and press power button on. The pre-loader rk2aw will show a graphical menu. Select _eMMC over USB_ or _SD over USB_ to expose the device to your computer. 

Make sure there are no signatures or partitions left with the command:

[source,console]
----
$ sudo wipefs /dev/$DEVICE
----

To erase all signatures, type:

[source,console]
----
$ sudo wipefs --all --force /dev/$DEVICE
----

Clean the device by overwriting the first sectors with zeroes:

[source,console]
----
$ sudo dd if=/dev/zero of=/dev/$DEVICE status=progress bs=32768 count=1
----

Optionally you can zeroes the whole device:

[source,console]
----
$ sudo dd if=/dev/zero of=/dev/$DEVICE status=progress bs=32768 count=$(expr $(lsblk -bno SIZE /dev/$DEVICE | head -1) \/ 32768)
----

=== Partitioning

Partition the device for the multiple distributions:

[source,shell]
----
$ sudo sfdisk /dev/$DEVICE --wipe always <<EOF
label: gpt
first-lba: 64
table-length: 8
attrs=RequiredPartition, type=D7B1F817-AA75-2F4F-830D-84818A145370, start=64, size=32704, name="uboot_raw"
attrs="RequiredPartition,LegacyBIOSBootable", size=$PARTSIZE, name="ppp-multi-image-arch"
attrs="RequiredPartition,LegacyBIOSBootable", size=$PARTSIZE, name="ppp-multi-image-manjaro"
attrs="RequiredPartition,LegacyBIOSBootable", size=$PARTSIZE, name="ppp-multi-image-mobian"
attrs="RequiredPartition,LegacyBIOSBootable", size=$PARTSIZE, name="ppp-multi-image-pmos"
attrs="RequiredPartition,LegacyBIOSBootable", size=$PARTSIZE, name="ppp-multi-image-sailfish"
attrs="RequiredPartition,LegacyBIOSBootable", size=$PARTSIZE, name="ppp-multi-image-ut"
attrs="RequiredPartition,LegacyBIOSBootable", size=+, name="extra"
EOF
----

Expected results:

[source,console]
----
Checking that no-one is using this disk right now ... OK
Disk /dev/sd[...]: 118.16 GiB, 126877696000 bytes, 247808000 sectors
Disk model: microSD card Reader  
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
>>> Script header accepted.
New situation:
Disklabel type: gpt
Disk identifier: A012E9D0-B4EB-4677-926F-D93AE4C696FA
 Device    Start       End  Sectors   Size Type
 sdb1         64     32767     32704   16M unknown
 sdb2      32768  23101439  23068672   11G Linux fs
 sdb3   23101440  46170111  23068672   11G Linux fs
 sdb4   46170112  69238783  23068672   11G Linux fs
 sdb5   69238784  92307455  23068672   11G Linux fs
 sdb6   92307456 115376127  23068672   11G Linux fs
 sdb7  115376128 138444799  23068672   11G Linux fs
 sdb8  138444800 247805951 109361152 52.1G Linux fs
The partition table has been altered.
Calling ioctl() to re-read partition table.
Syncing disks.
----

=== Install U-Boot

Your phone needs the link:/documentation/PinePhone_Pro/Software/Bootloaders/#install_u_boot[U-Boot bootloader] installed on the first sectors of the device.

=== Build the partitions

Make sure you download an updated file from link:/documentation/PinePhone_Pro/Software/Releases[relases download link].

==== Arch, Manjaro, Mobian, postmarketOS

For these distributions, download and decompress the image:

[source,console]
----
$ mkdir -p $WORKDIR/distros
$ cd $WORKDIR/distros
$ wget $DISTROURL 
$ xz -v -d -k IMAGE.*.xz
$ mv IMAGE.img $PARTNAME.img
----

Mount the image:

[source,console]
----
$ cd $WORKDIR/distros
$ sudo losetup -P /dev/loop0 $PARTNAME.img
$ sudo mkdir -p /mnt/$PARTNAME/boot /mnt/$PARTNAME/root /mnt/$PARTNAME/device
$ sudo mount /dev/loop0p1 /mnt/$PARTNAME/boot/
$ sudo mount /dev/loop0p2 /mnt/$PARTNAME/root/
----

Copy `rootfs` and `boot` contents:

[source,console]
----
$ sudo dd if=/dev/loop0p2 of=/dev/$DEVICE$PARTNUMBER bs=1M status=progress conv=fsync
$ sudo mount /dev/$DEVICE$PARTNUMBER /mnt/$PARTNAME/device/
$ sudo scp -r /mnt/$PARTNAME/boot/* /mnt/$PARTNAME/device/boot
----

==== SailfishOS

These distribution needs different commands. Download and decompress the image:

[source,console]
----
$ mkdir -p $WORKDIR/distros
$ cd $WORKDIR/distros
$ wget $DISTROURL -O artifacts.zip
$ unzip artifacts.zip
$ mv pinephonepro/*/sfe-pinephonepro*.tar.bz2 sailfish.tar.bz2
$ mkdir -p $WORKDIR/distros/sailfishos
$ tar -xvf sailfish.tar.bz2 -C sailfishos/ > /dev/null
----

Copy the extracted files directly onto the device:

[source,console]
----
$ sudo mkfs.ext4 -F /dev/$DEVICE$PARTNUMBER
$ sudo mkdir -p /mnt/$PARTNAME/device
$ sudo mount /dev/$DEVICE$PARTNUMBER /mnt/$PARTNAME/device
$ sudo rsync -avz --progress $WORKDIR/distros/sailfishos/ /mnt/$PARTNAME/device
----

==== All distributions

You also need some adjustments on _boot.scr_, _extlinux.conf_ and _fstab_ files.

Remame _/boot/boot*.scr_, if exists, to keep graphical menu clean:

[source,console]
----
$ [ ! -f /mnt/$PARTNAME/device/boot/boot.scr ] || sudo mv /mnt/$PARTNAME/device/boot/boot.scr /mnt/$PARTNAME/device/boot/boot.scr.bk
$ [ ! -f /mnt/$PARTNAME/device/boot/boot.pinephonepro.scr ] || sudo mv /mnt/$PARTNAME/device/boot/boot.pinephonepro.scr /mnt/$PARTNAME/device/boot/boot.pinephonepro.scr.bk
----

Rename the original _/boot/extlinux/extlinux.conf_ file, if exist:

[source,console]
----
$ sudo mkdir -p /mnt/$PARTNAME/device/boot/extlinux
$ [ ! -f /mnt/$PARTNAME/device/boot/extlinux/extlinux.conf ] || sudo mv /mnt/$PARTNAME/device/boot/extlinux/extlinux.conf /mnt/$PARTNAME/device/boot/extlinux/extlinux.conf.bk
----

Then write the new _/boot/extlinux/extlinux.conf_ file, making sure you remove `#` comment for the selected distributions:

[source,shell]
----
$ sudo tee /mnt/$PARTNAME/device/boot/extlinux/extlinux.conf <<EOF
#/boot/extlinux/extlinux.conf
menu title Pinephone Pro Boot Menu
label l0
menu label $MENUNAME

#uncomment next 3 lines for ARCH
#fdt /boot/dtbs/rockchip/rk3399-pinephone-pro.dtb
#initrd /boot/initramfs-linux.img
#kernel /boot/Image.gz

#uncomment next 3 lines for MANJARO
#fdt /boot/dtbs/rockchip/rk3399-pinephone-pro.dtb
#initrd /boot/initramfs-linux.img
#kernel /boot/Image

#uncomment next 3 lines for MOBIAN
#linux /boot/vmlinuz-6.6-rockchip
#initrd /boot/initrd.img-6.6-rockchip
#fdtdir /boot/dtb-6.6-rockchip/

#uncomment next 3 lines for PMOS
#fdtdir /boot/dtbs-pine64-pinephonepro/
#linux /boot/vmlinuz
#initrd /boot/initramfs-extra

#uncomment next 2 lines for SAILFISH
#fdt /boot/rockchip/rk3399-pinephone-pro.dtb
#kernel /boot/Image

append root=PARTLABEL=$PARTNAME console=ttyS2,115200 console=tty0 loglevel=7 rw rootwait

EOF
----

Rename the original _/etc/fstab_ file:

[source,console]
----
$ sudo mv /mnt/$PARTNAME/device/etc/fstab /mnt/$PARTNAME/device/etc/fstab.bk
----

Then write the new _/etc/fstab_ file, making sure you remove `#` comment for selected distribution:

[source,shell]
----
$ sudo tee /mnt/$PARTNAME/device/etc/fstab <<EOF
#<file system>         <dir>      <type> <options>                  <dump> <pass>

#uncomment next line for ARCH
#PARTLABEL=$PARTNAME   /          ext4   rw,relatime                0      1

#uncomment next line for MANJARO
#PARTLABEL=$PARTNAME     /          ext4   defaults                   0      1

#uncomment next line for MOBIAN
#PARTLABEL=$PARTNAME /          ext4   defaults,x-systemd.growfs  0      1

#uncomment next line for PMOS
#PARTLABEL=$PARTNAME   /          ext4   defaults                   0      0

#uncomment next 7 lines for SAILFISH
#PARTLABEL=$PARTNAME   /          ext4   rw,noatime                0      1
#devtmpfs   /dev      devtmpfs  nosuid               0 0
#devpts     /dev/pts  devpts  gid=5,mode=620         0 0
#tmpfs      /dev/shm  tmpfs   noexec,nosuid,nodev    0 0
#proc       /proc     proc    defaults         0 0
#sysfs      /sys      sysfs   defaults         0 0
#tmpfs      /tmp      tmpfs   nosuid,nodev           0 0

EOF
----

Close any mounted directory window.

==== Build the postmarketOS image

You can optionally use link:https://wiki.postmarketos.org/wiki/Pmbootstrap[pmbootstrap] to generate the distribution image on your Linux computer, instead of downloading a pre-made image. Make sure you install pmbootstrap before building the image.

Start creating 2 GB empty image file, format and mount it.

[source,console]
----
$ sudo su
# dd if=/dev/zero of=postmarketos.img bs=1 count=0 seek=2G status=progress && sync
# mkfs.ext4 postmarketos.img
# losetup -P /dev/loop0 postmarketos.img
# exit
----

Build the postmarketOS image via pmbootstrap:

[source,console]
----
$ pmbootstrap init
$ pmbootstrap status
$ pmbootstrap pull
$ pmbootstrap install --sdcard=/dev/[LOOP-DEVICE]
$ pmbootstrap shutdown
----

=== Unmount and detach

To unmount and deatch all building images, run:

[source,console]
----
$ sudo umount /mnt/$PARTNAME/*
$ sudo rm -r /mnt/$PARTNAME
$ sudo losetup -D
----

== Resizing the partitions

On the first boot, if it doesn't happen automatically, you can manually resize each image to fill the entire partition using GParted GUI software or using the CLI. Please note that SailfishOS doesn't need any resizing.

[source,console]
----
$ sudo e2fsck -f /dev/$DEVICE$PARTNUMBER
$ sudo resize2fs /dev/$DEVICE$PARTNUMBER
----

Repeat the building process for each needed distribution.

== Final notes

To find the exact _LABEL_, _UUID_, _PARTLABEL_ and _PARTUUID_ names, open a terminal window on the phone and use the command `blkid`.

Any time a distribution update rebuilds the initramfs it is necessary to delete _/boot/boot.scr_ again to keep the rk2aw menu clean.

In case you want to reinstall only one distribution, the easy way is to delete and recreate the selected partition using the GParted GUI.

Refer to link:/documentation/PinePhone_Pro/Troubleshooting[Troubleshooting] to get more help.
