---
title: "Introduction"
draft: false
menu:
  docs:
    title:
    parent: "PineBuds_Pro"
    identifier: "PineBuds_Pro/Introduction"
    weight: 1
---


General information and tips about PineBuds Pro.

=== Buttons/touch sensors


==== Buds

One capacitive touch sensor is located on the outward facing surface of each bud near the logo.

==== Charging case

Charging case have a reset button in center under the lid which is hooked to ThinkPlus Semi SY8821 integrated circuit and that button reset it from the safety off mode.

=== Cleaning

PineBuds Pro only have IPX4 rating, so they are only splash-proof and cannot withstand immersion in water. Clean the charging case inside and out with a damp microfiber cloth. Inside, be careful near the pogo pins|The cloth easily sticks to them and may tear them. You can use a microfiber cloth at the end of a stick to immerse of the buds, but a cleaning tool made for this can help. When cleaning the buds, carefully remove the tips, place the buds on a damp microfibre cloth and one by one wipe it from all sides. Be careful with the protective mesh. If there is dirt in the mesh, you can carefully clean it with the brush of the previously mentioned tool. Wash the tips with soap and water, but be careful, they easily drip from your hand to drain. After drying them, carefully put them back to the buds.

You need:

* A microfiber cloth
* A cleaning tool like https://www.aliexpress.com/item/1005004843772763.html[this] or https://www.aliexpress.com/item/1005004119111965.html[this]

