---
title: "Caring"
draft: false
menu:
  docs:
    title:
    parent: "Pinebook_Pro"
    identifier: "Pinebook_Pro/Caring"
    weight: 
---

=== Bypass Cables
The mainboard features two (disconnected by default) bypass cables that are only to be used with the battery disconnected. The female (10) male (6) ends of the bypass cables can be connected to provide power to the mainboard if you need to run the laptop without a battery. Please refer to this https://files.pine64.org/doc/PinebookPro/PinebookPro_Engineering_Notice.pdf[engineering notice].

*Note that despite the bypass cable being a two conductor cable, it is only used as one. Both wires being soldered together on either side is normal|*

WARNING: Do not connect the bypass cables with the battery connected. Using the bypass cables with the battery connected can permanently damage the computer.

=== Pinebook Service Step-by-Step Guides

These are instruction guides for the disassembly:

NOTE: The installation process is the reverse order of removal guide

* http://files.pine64.org/doc/pinebook/guide/Pinebook_14-Battery_Removal_Guide.pdf[Lithium Battery Pack Removal Guide]
* http://files.pine64.org/doc/pinebook/guide/Pinebook_14-Screen_Removal_Guide.pdf[LCD Panel Screen Removal Guide]
* http://files.pine64.org/doc/pinebook/guide/Pinebook_14-eMMC_Removal_Guide.pdf[eMMC Module Removal Removal Guide]

