---
title: "Touchpad"
draft: false
menu:
  docs:
    title:
    parent: "Pinebook_Pro"
    identifier: "Pinebook_Pro/Touchpad"
    weight: 
---

Documentation for the touchpad can be found in link:#Datasheets for Components and Peripherals[Datasheets for Components and Peripherals]. It is the only component of the Pinebook Pro held in place with strong adhesive tape. Here are some of its features:

* 2 actuating buttons.
* multi-touch functionality.
* A matte finish that your finger can slide along easily.
* A reasonable size (96mm × 64mm; diagonal: 115.378mm or 4.542”).

== Troubleshooting

If you are having trouble using 2 fingers to scroll or emulate the click of a mouse's right-button, then try these solutions:

* Update the firmware.
* Keep your 2 fingers spread apart rather than close together.
* Individual programs might need to be configured specially.
*. For smooth scrolling and gestures under X-Windows, _Firefox_ should be launched with with the following environment variable assignment:

::: `MOZ_USE_XINPUT2=1`

* Experiment with other settings, via link:#X-Windows_Configuration[X-Windows Configuration] or some other system preferences. For example, you could disable double-finger scrolling, and instead enable scrolling by sliding one finger along the edge of the touchpad.

== Firmware

The touchpad controller is connected to the keyboard controller. All touchpad events go through the keyboard controller and it's software, then to the keyboard controller's USB port. Note that the touchpad does have separate firmware (which has to be written through the keyboard controller). The touchpad vendor's firmware binary can be flashed from userspace using the following open source command-line utility:

* Kamil Trzciński's https://github.com/ayufan-rock64/pinebook-pro-keyboard-updater[pinebook-pro-keyboard-updater].

Naturally, forks have begun to appear:

* Jack Humbert's https://github.com/jackhumbert/pinebook-pro-keyboard-updater[fork]

* Dragan Simic's https://github.com/dragan-simic/pinebook-pro-keyboard-updater[fork]. This one has recently delivered a much improved firmware from the vendor one, which greatly improves the control of the cursor (see this https://forum.pine64.org/showthread.php?tid=14531[thread] for discussion). Before installing this update, consider resetting to the defaults any configuration of your touchpad.

*Every Pinebook Pro produced before September 2021 should have its keyboard and touchpad firmware updated.*

WARNING: DO NOT update the touchpad firmware before checking which keyboard IC your Pinebook Pro has. Some Pinebook Pro were delivered with a _SH61F83_ instead of a _SH68F83_. The SH61F83 can only be written 8 times, this will render the keyboard and touchpad unusable if this limit is reached when step 1 (see below) is flashed. See https://reddit.com/r/PINE64official/comments/loq4db/very_disappointed/[Reddit SH61F83 thread]. The keyboard IC corresponds to _U23_ on the link:#Pinebook_Pro_Schematics_and_Certifications[top layer silkscreen of the main board]. It is located under the keyboard flat flexible cable.

Before updating _any_ firmware, your Pinebook Pro should be either fully charged or, preferably, running from mains. This utility will be writing data to chips on the keyboard and touchpad, so a loss of power during any stage of the update can result in irrecoverable damage to your touchpad or keyboard.

The scripts ought to work on all operating systems available for the Pinebook Pro. Some operating systems may however, require installation of relevant dependencies. The instructions below assume a Debian desktop. To install these dependencies, newer Pinebook Pro models that come with Manjaro will require a different command.

There are two keyboard versions of the Pinebook Pro: ISO and ANSI. You need to know which model you have prior to running the updater.
Firmware update steps for both models are listed below.

*TODO* Explain how one can know which keyboard model he has.

What you will need:

* Connection to internet for getting dependencies, either through WIFI or wired ethernet (USB dongle).
* Your Pinebook Pro fully charged or running from mains power.
* An external USB keyboard and mouse (or access to the Pinebook Pro via SSH. Please note that for some configurations, the SSH service might not be available without first having logged in once. In this case, you will definitely want at least an external keyboard).

=== ISO Model

From the terminal command line:

 git clone https://github.com/ayufan-rock64/pinebook-pro-keyboard-updater
 cd pinebook-pro-keyboard-updater
 sudo apt-get install build-essential libusb-1.0-0-dev xxd
 make

Step 1

 cd pinebook-pro-keyboard-updater
 sudo ./updater step-1 iso
 sudo poweroff # do not use 'reboot'

Step 2 (after booting)

 cd pinebook-pro-keyboard-updater
 sudo ./updater step-2 iso
 sudo poweroff # do not use 'reboot'

=== ANSI Model

IMPORTANT: 

From the terminal command line:

 git clone https://github.com/ayufan-rock64/pinebook-pro-keyboard-updater
 cd pinebook-pro-keyboard-updater
 sudo apt-get install build-essential libusb-1.0-0-dev xxd
 make

Step 1

 cd pinebook-pro-keyboard-updater
 sudo ./updater step-1 ansi
 sudo poweroff # do not use 'reboot'

Step 2 (after booting)

 cd pinebook-pro-keyboard-updater
 sudo ./updater step-2 ansi
 sudo poweroff # do not use 'reboot'

When done, if some of the keys produce incorrect characters, please check your OS’s language settings. For ANSI users, the default OS may have shipped with English UK as the default language. You can change it to English US if desired.

=== Revised Firmware

In addition, you might consider using revised firmware data. This is one final step that should not require a reboot:

Step 3: *ISO* (after booting)

 sudo ./updater flash-kb firmware/default_iso.hex

Step 3: *ANSI* (after booting)

 sudo ./updater flash-kb firmware/default_ansi.hex

== X-Windows Configuration

NOTE: Before making adjustments, consider updating the firmware. Reset your adjustments before updating the firmware, so that your adjustments do not interfere with new functionality.

Some forum members have found that an adjustment to X-Windows will allow finer motion in the touchpad. If you use the _Synaptic_ mouse/touchpad driver, use this command to make the change live:

 synclient MinSpeed=0.2

You may experiment with different settings, but 0.25 was tested as helping noticeably.

To make the change persist across reboots, change the file */etc/X11/xorg.conf* similar to below:

 Section "InputClass"
        Identifier "touchpad catchall"
        Driver "synaptics"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        *Option "MinSpeed" "0.25"*
 EndSection

The line "Option "MinSpeed" "0.25"" is changed here.

Another forum user built on the above settings a little, and have found these to be very good:

 synclient MinSpeed=0.25
 synclient TapButton1
 synclient TapButton2=3
 synclient TapButton3=2
 synclient FingerLow=30
 synclient PalmDetect=1
 synclient VertScrollDelta=64
 synclient HorizScrollDelta=64

_FingerLow_ has the same value as 'FingerHigh' in one config (30). It is believed to help reduce mouse movement as you lift your finger, but it's unknown whether synaptic works like this.
You may find this config to be comfortable for daily use.

_TabButton_ allows to just tab the touchpad instead of physically pressing it down (to get this click noise).

The right mouse click is emulated by tapping with two fingers on the touchpad. If you feel that this is not very responsive you can try this value:

 synclient MaxTapTime=250

Some users may encounter an issue with the mouse jumping when typing when using libinput driver (has not been test with synaptic) due to their hand hitting the touchpad which can be fixed by updating the X.Org settings to disable it while typing. One can disable the touchpad while typing by setting the below option in the X.Org config simliar to the previous example.

         Option "DisableWhileTyping" "on"

The setting can be verified by using the xinput command to first list the devices and then listing the properties for the touchpad device. Exact commands to check this have been omitted for save of brevity. If DisableWhileTyping is shown enabled but does not appear to be working the issue may be due to the fact that the keyboard is connected to a USB bus which causes it to be seen as a external keyboard. To resolve this one can add the config below which sets the keyboard to internal to ensure the DisableWhileTyping works properly.

You will need to edit */etc/libinput/local-overrides.quirks* and add the following lines:

 [Serial Keyboards]
 MatchUdevType=keyboard
 MatchBus=usb
 AttrKeyboardIntegration=internal

Once X11 is restarted the new setting should now take effect and you will no longer be able to use the touchpad while typing which will mostly eliminate the mouse jumping issue.

