---
title: "Multi-distribution image"
draft: false
menu:
  docs:
    title:
    parent: "PinePhone_Pro/Various"
    identifier: "PinePhone_Pro/Various/Multi-distribution_image"
    weight: 
---

This article explains how to install a multiple linux distribution enviroment on your PinePhone Pro that is bootable from a microSD card.

== Install rk2aw

Make sure your phone has the link:/documentation/PinePhone_Pro/Software/Bootloaders/#rk2aw[rk2aw pre-loader] installed to SPI flash. PinePhone Pro models ordered after November 2023 are shipped with rk2aw pre-installed. Otherwise, follow the instructions in this section to install it.

TIP: The multi-boot image _can_ function without rk2aw, but you may need to hold down the **RE** button during boot.

Please note that rk2aw and the userspace utility to flash it are free, but not open-source. They are supplied to the end user in binary form under the MIT license.

Open the terminal application on your PinePhone Pro's stock operating system and make sure the phone’s SSH server is up and running.

 sudo apt install ssh
 sudo systemctl enable --now sshd
 ip address # phone's ip address
 whoami # user name

Open a terminal window on your Linux computer.

 ssh USER@PHONEIP # start ssh connection
 mkdir -p ~/rk2aw
 cd ~/rk2aw
 curl -O https://xff.cz/kernels/bootloaders-2024.04/ppp.tar.gz
 tar -xvzf ppp.tar.gz -C ~/rk2aw
 cd ~/rk2aw/ppp
 sudo ./spinor-flash-initial-setup.sh

Further instructions can be found on the link:https://xff.cz/kernels/bootloaders-2024.04/ppp/rk2aw/INSTALL[author's website].

== Build multi-distro microSD card

Insert microSD card into the Linux computer. Make sure there are no signatures or partitions left. Format cleared any partition using GParted GUI. Than open terminal window to wipe any content.

 lsblk # shows the device name 
 
 sudo wipefs /dev/[DEVICE] # shows current signatures
 sudo wipefs --all --force /dev/[DEVICE] # erase current signatures

Zero-write the microSD card

 sudo dd if=/dev/zero of=/dev/[DEVICE] status=progress bs=32768 count=1 # quick way erasing
 sudo dd if=/dev/zero of=/dev/[DEVICE] status=progress bs=32768 count=$(expr $(lsblk -bno SIZE /dev/[DEVICE] | head -1) \/ 32768) # full erase

=== Partition the microSD card

 PARTSIZE=16G # adjust depending on microSD card size
 
 sudo sfdisk /dev/[DEVICE] --wipe always <<EOF
  label: gpt
  first-lba: 64
  table-length: 8
  attrs=RequiredPartition, type=D7B1F817-AA75-2F4F-830D-84818A145370, start=64, size=32704, name="uboot_raw"
  attrs="RequiredPartition,LegacyBIOSBootable", size=$PARTSIZE, name="ARCH"
  attrs="RequiredPartition,LegacyBIOSBootable", size=$PARTSIZE, name="MANJARO"
  attrs="RequiredPartition,LegacyBIOSBootable", size=$PARTSIZE, name="MOBIAN"
  attrs="RequiredPartition,LegacyBIOSBootable", size=$PARTSIZE, name="PMOS"
  attrs="RequiredPartition,LegacyBIOSBootable", size=$PARTSIZE, name="UT"
  attrs="RequiredPartition,LegacyBIOSBootable", size=+, name="extra"
 EOF

NOTE: Make sure you will use correct partition `name` into `PARTNAME` and `PARTNUMBER` during building.

NOTE: A minimum capacity of 64 GB for the microSD card is recommended for 5 distributions.

Expected result

 Checking that no-one is using this disk right now ... OK
 Disk /dev/sdb: 118.16 GiB, 126877696000 bytes, 247808000 sectors
 Disk model: microSD card Reader  
 Units: sectors of 1 * 512 = 512 bytes
 Sector size (logical/physical): 512 bytes / 512 bytes
 I/O size (minimum/optimal): 512 bytes / 512 bytes
 >>> Script header accepted.
 New situation:
 Disklabel type: gpt
 Disk identifier: A012E9D0-B4EB-4677-926F-D93AE4C696FA
  Device    Start       End  Sectors   Size Type
  sdb1         64     32767    32704   16M  unknown
  sdb2      32768  33587199 33554432   16G  Linux fs
  sdb3   33587200  67141631 33554432   16G  Linux fs
  sdb4   67141632 100696063 33554432   16G  Linux fs
  sdb5  100696064 134250495 33554432   16G  Linux fs
  sdb6  134250496 167804927 33554432   16G  Linux fs
  sdb7  167804928 247805951 80001024 38.1G  Linux fs
 The partition table has been altered.
 Calling ioctl() to re-read partition table.
 Syncing disks.

=== Install U-Boot to the microSD card

Download the following U-Boot build. The source code can be found https://xff.cz/git/u-boot/tree/?h=ppp-2023.07[here].

 cd ~/rk2aw
 curl -O https://xff.cz/kernels/bootloaders-2024.04/ppp.tar.gz
 tar -xzf ppp.tar.gz

NOTE: This is the same `ppp.tar.gz` from the <<install_rk2aw>> section; if you already have a copy of it on your computer then you don't have to download it again.

NOTE: If you are interested in building this U-Boot image yourself, you will need to copy the `ppp/foss/.config` file from the archive above to the root of your U-Boot source directory.

Write the U-Boot image to the microSD card.

 sudo dd if=ppp/foss/u-boot-rockchip.bin of=/dev/[DEVICE] bs=512 seek=64
 sudo sync

=== Building partition for each linux distribution

Download, decompress and mount the distribution image on your Linux computer. Copy root filesystem and boot to needed partition. Replace/create `/boot/extlinux/extlinux.conf` and `/etc/fstab` files. Make sure you use an updated image from link:/documentation/PinePhone_Pro/Software/Releases[relases download link] for each distribution. This guide has been tested with following images:

* https://github.com/dreemurrs-embedded/Pine64-Arch/releases/download/20230925/archlinux-pinephone-pro-phosh-20230925.img.xz
* https://github.com/manjaro-pinephone/phosh/releases/download/beta37/Manjaro-ARM-phosh-pinephonepro-beta37.img.xz
* https://images.mobian.org/pinephonepro/weekly/mobian-pinephonepro-phosh-20240121.img.xz
* https://images.postmarketos.org/bpo/v23.12/pine64-pinephonepro/phosh/20240221-0448/20240221-0448-postmarketOS-v23.12-phosh-22.3-pine64-pinephonepro.img.xz
* (https://ci.ubports.com/job/focal-hybris-rootfs-arm64/job/master/lastSuccessfulBuild/artifact/ubuntu-touch-pinephone-pro-img-arm64.raw.xz) Note: this distribution currently doesn't work on the multi-distro image

Replace the VALUES according the updated distribution and real file name:

 DISTROURL=image_url_address
 PARTNAME=ARCH
 PARTNUMBER=2

 mkdir -p ~/ppp/distros
 cd ~/ppp/distros
 wget $DISTROURL
 xz -v -d -k IMAGE.*.xz
 mv IMAGE.img $PARTNAME.img

 sudo losetup -P /dev/loop0 $PARTNAME.img
 sudo mkdir -p /mnt/$PARTNAME/boot /mnt/$PARTNAME/root /mnt/$PARTNAME/sd
 sudo mount /dev/loop0p1 /mnt/$PARTNAME/boot/ # use loop0p2 for UT
 sudo mount /dev/loop0p2 /mnt/$PARTNAME/root/ # use loop0p3 for UT

 sudo dd if=/dev/loop0p2 of=/dev/[DEVICE]$PARTNUMBER bs=1M status=progress conv=fsync # use loop0p3 for UT
 sudo mount /dev/[DEVICE]$PARTNUMBER /mnt/$PARTNAME/sd/
 sudo scp -r /mnt/$PARTNAME/boot/* /mnt/$PARTNAME/sd/boot
 # sudo mv /mnt/$PARTNAME/sd/boot/boot.scr /mnt/$PARTNAME/sd/boot/boot.scrORIG # rename if present
 sudo mkdir -p /mnt/$PARTNAME/sd/boot/extlinux
 # sudo mv /mnt/$PARTNAME/sd/boot/extlinux/extlinux.conf /mnt/$PARTNAME/sd/boot/extlinux/extlinux.confORIG # rename if present
 # sudo mv /mnt/$PARTNAME/sd/etc/fstab /mnt/$PARTNAME/sd/etc/fstabORIG # rename

 sudo tee /mnt/$PARTNAME/sd/boot/extlinux/extlinux.conf <<EOF
 #/boot/extlinux/extlinux.conf
 menu title Pinephone Pro Boot Menu
 label l0
 menu label $PARTNAME
 #
 #uncomment for ARCH, MANJARO
 #fdt /boot/dtbs/rockchip/rk3399-pinephone-pro.dtb
 #initrd /boot/initramfs-linux.img
 #
 #uncomment for ARCH
 #kernel /boot/Image.gz
 #
 #uncomment for MANJARO
 #kernel /boot/Image
 #
 #uncomment for MOBIAN
 #linux /boot/vmlinuz-6.6-rockchip
 #initrd /boot/initrd.img-6.6-rockchip
 #fdtdir /boot/dtb-6.6-rockchip/
 #
 #uncomment for PMOS
 #fdtdir /boot/dtbs-pine64-pinephonepro/
 #linux /boot/vmlinuz
 #initrd /boot/initramfs-extra
 #
 #uncomment for ARCH, MANJARO, MOBIAN, PMOS
 #append root=PARTLABEL=$PARTNAME console=ttyS2,115200 console=tty0 loglevel=7 rw rootwait
 #
 #uncomment for UT
 #linux /boot/vmlinuz-6.5.0-okpine-ut
 #initrd /boot/initrd.img-6.5.0-okpine-ut
 #fdtdir /boot/dtb-6.5.0-okpine-ut/	
 #append root=PARTLABEL=$PARTNAME console=ttyS2,115200 consoleblank=0 loglevel=7 systempart=/dev/disk/by-partlabel/system datapart=/dev/disk/by-partlabel/userdata security=apparmor splash plymouth.ignore-serial-consoles vt.global_cursor_default=0
 EOF

 sudo tee /mnt/$PARTNAME/sd/etc/fstab <<EOF
 #<file system>         <dir>      <type> <options>                  <dump> <pass>
 #uncomment for ARCH
 #PARTLABEL=$PARTNAME   /          ext4   rw,relatime                0      1
 #
 #uncomment for MANJARO
 #PARTLABEL=MANJARO     /          ext4   defaults                   0      1
 #
 #uncomment for MOBIAN
 #PARTLABEL=$PARTNAME   /          ext4   defaults,x-systemd.growfs  0      1
 #
 #uncomment for PMOS
 #PARTLABEL=$PARTNAME   /          ext4   defaults                   0      0
 #
 #uncomment for UT
 #PARTLABEL=$PARTNAME   /          ext4   defaults                   0      1
 #PARTLABEL=$PARTNAME   /boot      ext4   defaults                   0      2
 #PARTLABEL=$PARTNAME   /userdata  ext4   defaults                   0      2
 EOF

=== Unmount, detach all building images and resize partition.

 sudo umount /mnt/$PARTNAME/*
 sudo rm -r /mnt/$PARTNAME
 sudo losetup -D

On the first boot, if it doesn't happen automatically, you can manually resize each image to fill the entire partition using GParted GUI software or using the CLI:

 sudo e2fsck -f /dev/[DEVICE]$PARTNUMBER
 sudo resize2fs /dev/[DEVICE]$PARTNUMBER

Repeat the building process for each needed distribution.

=== Build PostmarketOS image

You can optionally use bootstrap to generate distro image on your Linux computer, instead of direct download. Make sure you install pmbootstrap before building image.

 git clone --depth=1 https://git.sr.ht/~postmarketos/pmbootstrap
 mkdir -p ~/.local/bin
 ln -s "$PWD/pmbootstrap/pmbootstrap.py" ~/.local/bin/pmbootstrap
 source ~/.profile # remember to update your environment
 pmbootstrap --version # if this returns error see next command

 sudo tee -a ~/.profile <<EOF
  PATH="$HOME/.local/bin:$PATH"
 EOF

Start creating 2 GB empty image file, format and mount it.

 sudo su
 dd if=/dev/zero of=postmarketos.img bs=1 count=0 seek=2G status=progress && sync
 mkfs.ext4 postmarketos.img
 losetup -P /dev/loop0 postmarketos.img
 exit

Build PostmarketOS image via pmbootstrap

 pmbootstrap init # follow all the setup directions
 pmbootstrap status
 pmbootstrap pull
 pmbootstrap install --sdcard=/dev/loop0
 pmbootstrap shutdown # remember to deactivare chroot after the image creation
 
== Switching on device

According to megi's link:https://xnux.eu/rk2aw[rk2aw info], use the power button and LED feedback to operate the PinePhone Pro:

* Plug in USB power cord. The LED blinks: 0.5s on, 0.5s off. Battery is slowly charging.
* Press shortly power button. The graphical menu appears, than just select the image to boot from.
* Press longer power button, LED starts to blinks rapidly. Release the power button, LED blinks N times each second depending on the selected image.

For example:

* LED blinks once each second and 1st image is selected;
* LED blinks twice each second and 2nd image is seleted;
* LED blinks triple each second and 3rd image is selected.
* Press shortly to move to next image.
* Press longer to boot the selected image.
* In case you hold the power button too long, the device is forced to power off.

== Troubleshooting

To find the exact LABEL, UUID, PARTLABEL, PARTUUID names open a terminal window.

 ssh USER@PHONEIP
 sudo blkid

Any time a distribution update rebuilds the initramfs it is necessary to delete `/boot/boot.scr` again to keep the rk2aw menu clean.

In case you want to reinstall only one distribution, the easy way is to delete and recreate the selected partition using the GParted GUI.

If the device doesn't start, connect a compatible link:https://pine64.com/product/pinebook-pinephone-pinetab-serial-console[serial cable] to the headphone jack and a computer, switch off microswitch 6 and start a serial console to investigate further. Find out the corresponding usb device from the CLI and then connect to it using for example _minicom_:

 ls /dev/ttyUSB*
 minicom -b 1500000 -D /dev/ttyUSB[x]
