---
title: "PINE64 Community Rules and Code of Conduct"
draft: false
menu:
  docs:
    title:
    parent: "General"
    identifier: "General/Rules"
    weight: 
---

These rules apply to all official PINE64 platforms and protocols facilitating social interactions, and will be enforced by moderators at all times. Failure to comply with these rules may result in a temporary or permanent ban from all PINE64 community platforms. If deemed necessary, a permanent ban can be issued without a prior notice. In extreme circumstances - such as those involving threats or hate speech - the Pine Store reserves the right to deny service to the offending party and notify local or regional authorities.

== Foreword

We trust in people's common sense. There are intangible subtleties in human interactions that make a behaviour ‘OK’ at one time but not at others, and no artificial list of social-engagement rules, no matter how extensive, could capture this complexity accurately. To this end, we ask that you stay mindful of people’s sensitivities and address others respectfully at all times.
Moderators are tasked with facilitating discussion, maintaining order and keeping the debate on-topic. They also have the necessary tools to enforce these rules at their discretion. The official forum, subreddit(s) and some chat protocols have systems dedicated to issuing warnings. In the absence of a formal moderation system, a moderator may reach out to a user directly via PM/ DM to issue a warning. In extreme circumstances, moderation actions will be taken without issuing prior warnings.
Lastly, keep in mind that moderators have no power to make someone a friendly or nice human being (this was the said person's parents' job). Being an unsympathetic or crude person is not an actionable offense from a moderation standpoint. Hint: some chat protocols also give you the option to mute messages from select users.

== 1) General Rules

* *Read the rules* before posting on the forum, the subreddit(s) or engaging in the chat(s).
* *Be respectful to other community members.* Discourse is always a good thing, and sharing your opinions and insight is valuable to us and our user base. But how you engage with others is just as important as the ideas you share. We pride ourselves on this being a friendly community, and we will take measures to maintain it this way.
* *Stay on topic.* If a topic is set for a forum thread or discussion group/ channel then stick to it. Want to talk about something else? - there is an #offtopic chat on our Discord and IRC, and a Community and Events section on the forums.
* *Write in English.* Unless the subforum or chat specifies a different language, please stick to using English. There are numerous unofficial PINE64-product forums and chats catering to end-users who prefer communicating in a different language. If there isn’t a discussion group in your native tongue, why not start one?
* *Watch your language.* Some of our community members are younger than others; expletives are not necessary to communicate your viewpoints or experience. Please avoid using curse words, thank you.
* Use the search feature before posting or asking. The official PINE64 form and various chat protocols offer a search feature. If you’re looking for information, before you ask, try searching for the key words related to your query first - it is likely the topic you’re interested in has already been discussed.
* *Obey platform-specific rules.* Some communication platforms may have additional rules in place. For instance, you may not ping everyone in Discord chat using the @everyone function or paste lengthy log print-outs in Matrix. Where applicable, chat or forum-specific rules need to be followed.
* *Ask If you are unsure.* If you are unsure about where to best ask your question, or you are not sure if the topic is compliant with our rules and code of conduct, then please first reach out to someone on our moderation team. Moderators are always clearly demarcated on the various social interaction platforms.
* *Stay on-topic.* The chats and forum have clearly designated topics related to hardware and software. It is expected that you stay on-topic in the individual chats or forum sub-sections, and that you refrain from posting off-comments that divert the discussion towards an irrelevant subject (sometimes called 'hijacking'). Some chat platforms offer an 'off-topic' channel, and here on the forum there is a 'community' sub-section, where subjects not directly related to hardware and software can be discussed (granted it does not violate any of the rules contained within this post).

== 2) Form and Content

* *Use standard formatting.* You should adhere to platform standard formatting, such as default font, font-size, font-colour, line spacing, etc. Content written in all CAPS or in rainbow colours is at a risk of being permanently removed by moderators. Making your writing easily legible also helps with getting your query answered.
* *Describe your problem* and don’t ask if you may ask a question. When stating your query, make sure to describe the issues you’re experiencing and the trouble-shooting steps you already attempted. In the chat: don’t ask for permission to ask, just state your problem. If your question is directed at a particular person, make sure to use @ their username or handle to get their attention.
* *Do not post any knowingly false or inaccurate material.* This is self-explanatory. Posting information that is false may get you suspended or banned from our platforms.
* *Do not post or distribute copyrighted or stolen material.* Links to stolen material, be it images, video, plagiarized written content or pirated software will be removed immediately. Posting such content may result in a temporary or permanent suspension from all our PINE64 community platforms.
* *Signatures are allowed on the forum.* Please be mindful that your signature has to comply with all rules, just as any other content you submit on the official forum. You may, however, be asked by a member of the moderation team to alter your forum signature if it affects legibility of posted content.
* *No advertisements of non-FOSS and commercial products.* You are welcome to let people know about your FOSS project, as well as any FOSS/OSH hardware project, but other types of advertisements will be removed immediately. If deemed as spam, posting such content may result in a temporary or permanent ban on all our platforms.
* *Images and other media are best shared via links.* It is always best to upload your videos or images and link them on the forum or in the chats. While attachments can be uploaded on the forum, they are limited to 2MB total per post. The different chat protocols handle attachments differently, which may lead to the content not displaying across the chat protocol bridge.
* *No politics, religion or other sensitive topics* is permissible on any of our platforms. Simply put, there are better places to discuss such topics. This rule also applies to #OffTopic chat and Community and Events subforum. Posts referring to such subject matter will be removed and may result in a warning, and even a temporary ban if the activity does not cease.
* *No offensive nicknames, account names or online handles.* If your online handle includes curse words, inappropriate imagery, inappropriate or offensive mockery, or otherwise relates to sensitive subject matter you may be asked to change your handle (or the Admin may change it for you). Not complying with the request will be met with a warning, followed by a ban on all platforms.
* *Moderation of heated discussions.* In general, if a discussion is heated (and doesn’t violate any of our rules or general code of conduct) but productive, then the moderation team will not intervene. There are, however, instances where a heated discussion is either moot or likely to take a turn for the worse; in such an event a moderator may ask for a halt to the conversation. One moderator may deem a heated discussion to be in a good spirit, while another moderator may ask for the discussion to cease. The decision to stop the conversation is completely at the moderator’s discretion.

== 3) Spam, Illegal and Inappropriate Content

* *Automated spam (bots).* We employ an automated spam protection as well as other measures that prevent new accounts from spamming the official PINE64 forum. New user’s posts need to be manually approved by the moderation team for a period of 3 days. Automated spam in the chats needs to be reported to the moderation team. We always strive to remove the spam and the bots as soon as possible. An IP associated with spam bots will be IP-banned.
* *Spamming by end-users.* Accidental or uninformed ‘spam’ - such as, for instance, pastes of lengthy log print-outs - may be removed by moderators, if it affects legibility of the chat. Use pastebin or similar to share a link with logs.
* *Trolling.* Trolling is defined as posting inflammatory messages to cause havoc in the community. Posting such content will result in a temporary or permanent ban from all PINE64 community platforms.
* *Illegal* content of any kind will be removed immediately and lead to permanent ban on all our platforms. If you encounter any illegal content on the official forum, subreddit or in the chat please report it immediately to the moderation team. In instances where it is applicable, the content itself and the associated account which submitted the post will be reported to the relevant regulator or local authorities.
* *Sexual content.* Any form of sexual content - in written, video or photographic format - is not allowed on our platforms. Posting sexual content will result in an instant ban on all PINE64 platforms.

== 4) Threats, Hate Speech, Bullying and Harassment

* *Threats of any kind* will result in an instant ban from all PINE64 platforms. Threats made may also be reported to local or regional authorities by the moderation team, if they are deemed legitimate or/ and a cause of psychological distress.
* *Any form of hate speech* will result in an instantaneous ban on all our platforms and may be reported to local or regional authorities by the moderation team. Hate speech is a crime in most of the civilized world.
* *Discrimination of any kind.* Any forms or discrimination including, but not limited to, misogyny, sexism, racism, xeniophobia and agism will result in an instant ban across all of PINE64 platforms.
* *Bullying.* We will not stand for bullying of any kind on our community communication platforms. Every community member can rest assured that they can express themselves and their viewpoints without being made fun of or ridiculed. If you have been the subject of or witnessed to behaviour, please report it to the moderation team. Bullying will result in an instant ban on all PINE64 platforms.
* *Harassment*, defined as any behaviour aimed at intimidating or humiliating another community member, needs to be immediately reported to the moderation team. If moderators determine that the offending party’s actions were designed to purposefully humiliate and intimidate another community member, then a subsequent ban from all PINE64 platforms will be enforced.
* *Slander* of fellow community members, Pine Store contractors and moderation team members will result in warning and, if the situation is not rectified, a permanent ban spanning all PINE64 social platforms. Slander is defined as: a knowingly false statement designed to damage reputation.

== 5) Privacy

* *Private details.* Any materials made public on purpose or by accident which contains private or otherwise identifying information will be removed from our platform without prior notice. We define private details as information that includes, but is not limited to, phone numbers, emails, shipping addresses or IP address. For example: if you post a video of an unboxing where you inadvertently show your shipping address, the moderation team will pull the video down to preserve your privacy. If you encounter such content, please notify the moderation team.
* *Materials under NDA or Embargo.* Any confidential materials issued under an NDA are subject to removal from our community platforms without notifying the original poster. Such materials may include documents (e.g. schematics), schematics of unreleased devices, images of prototypes or written descriptions of unannounced devices.

== 6) Software Feedback

* *Software feedback.* We and our partner projects value your feedback, but this feedback needs to be communicated in a structured and respectful manner. When addressing developers on our platforms please make sure to formulate your feedback and criticism in a constructive manner. Everyone has their favorite distribution, desktop environment and software implementations. This, however, doesn’t mean that alternatives to your favorite software should be taunted or ridiculed; ultimately, everyone is working towards a common goal and everyone’s work ought to be respected. In short, stay respectful of people’s work.
* *Software feature requests*, similarly to feedback, should be relayed in a respectful and considerate manner. Keep in mind that many developers working on PINE64 hardware do so in their spare time, on limited resources and are offering their software as a service to this community. No user has ‘a right to demand’ inclusion of software features.
* *Reporting bugs.* The PINE64 official forum and chats aren’t the ideal place to report bugs or other software issues. You are, of course, welcome to notify developers of the issues you encountered on the forum or in the chats, but ultimately this should be accompanied by submission of a bug report on GitHub and the software project’s forum.
* *Adhere to partner project’s rules* when engaging with their community on their social interaction platforms. Partner project’s forums and chats may be subject to different communication rules than our own; we ask you to stay mindful of this when discussing software designed for our devices outside of the PINE64 community platform.