---
title: "S01E09: Eventful Number 9"
date: 2021-05-21
draft: false
description: "In the this episode Peter and Ezra discuss two conferences that happened recently, the May PINE64 Community Update and some more community news. They also answer four community questions and ask kindly for more!"
aliases:
    - /podcast/009-eventful-no-9/
---

{{< podcast_player episode="s01e09">}}

In this episode nine Peter and Ezra discuss two conferences that happened recently, the May PINE64 Community Update and some more community news. They also answer four community questions and ask kindly for more!

== What have we been up to lately?

* Ezra is still working on his point and click adventure game and attended the Linux App Summit.
** Check out what Ezra does on https://elatronion.com/[Elatronion.com], https://odysee.com/@Elatronion:a[Odysee] and https://www.youtube.com/channel/UCLN0SPhQo4jAPpTFNsxUnMg[YouTube]!
* Peter was quite busy with family matters, and only managed to write
** https://linmob.net/linbits45-weekly-linux-phone-news-week19/[LinBits 45: Weekly Linux Phone news / media roundup (week 19)],
** https://linmob.net/linmobapps-additions-changes-march-april-2021/#the-future-linuxphoneapps-org[LINMOBapps: Additions in March and April 2021 and future plans]. 

== App of the Episode

* https://agregore.mauve.moe/[Agregore Browser] by https://twitter.com/RangerMauve[Ranger Mauve]
** https://github.com/AgregoreWeb/agregore-browser/[GitHub]
** https://www.youtube.com/watch?v=TnYKvOQB0ts[Dat Conference talk]

== Topics:
=== Linux App Summit

https://linuxappsummit.org/[Linux App Summit]

* Thank you to https://conf.linuxappsummit.org/event/3/timetable/#all[NerdZoom Media] for being our audio producers! https://conf.linuxappsummit.org/event/3/timetable/#all[Full schedule]
* https://www.youtube.com/channel/UCjSsbz2TDxIxBEarbDzNQ4w[YouTube channel]
* Panel discussion: Building International Software Communities by Aniqa Khokhar et al.
** https://www.youtube.com/watch?v=bngxw7n5imQ[Video recording]
* Forcing Hardware Vendors to care about Linux since 2015 by Richard Hughes
** https://conf.linuxappsummit.org/event/3/contributions/64/attachments/22/44/22%20richard%20hughes%20Building%20the%20LVFS.pdf[Slides]
** https://www.youtube.com/watch?v=PnIQT0CMado[Video recording]
* Adaptive Apps: The Future Is Now by Tobias Bernard
** https://conf.linuxappsummit.org/event/3/contributions/49/attachments/12/38/1%20tobias%20bernard%20adaptive-apps.pdf[Slides]
** https://www.youtube.com/watch?v=piE4JJ_BskI[Video recording]
* Funding Krita by Halla Rempt
** https://conf.linuxappsummit.org/event/3/contributions/52/attachments/14/41/4%20halla%20rempt%20LAS_2021_Funding_Krita.pdf[Slides]
** https://www.youtube.com/watch?v=iIvGH_fnVtI&list=PL3sxxpspw7FEQ4-N3ugzfq0o55Kpz3_EN&index=5[Video recording]

=== AlpineConf 2021

https://alpinelinux.org/conf/[AlpineConf 2021]

Recordings:

* https://www.youtube.com/watch?v=WH0SU0eRSbA[AlpineConf - Oliver Smith - pmbootstrap: the Swiss Army knife of postmarketOS development]
* https://www.youtube.com/watch?v=npKwMWr1F_0[AlpineConf - Martijn Braam - Showing off postmarketOS]
* https://diode.zone/videos/watch/3f0948cf-47df-437e-b1ea-76fec58479c2[Sxmo: Simple X Mobile - A minimalist environment for Linux smartphones]
* https://bbb.dereferenced.org/b/adm-ec4-bx7-ypm[Big Blue Button room recordings]

We have links to the video recordings, the https://bbb.dereferenced.org/b/adm-ec4-bx7-ypm[Big Blue Button room recordings] (which contain the Q&As) and the conference itself in the shownotes.

=== PINE64 Community Update May

https://www.pine64.org/2021/05/15/may-update-connection-established/[PINE64 Community Update May: Connection established]

* Video by PizzaLovingNerd:
** https://tilvids.com/videos/watch/5f20d305-4311-4680-8c7d-5a9ad1354e79[Tilvids]
** https://www.youtube.com/watch?v=z-MQO7xOemQ[YouTube]
** https://odysee.com/@PINE64:a/may-update-insert-title-here:5[Odysee]

==== PineTime

* https://twitter.com/AlexRob12252696/status/1394754490927095808[Siglo 0.8.0 was released shortly before our recording], so some of these pull requests have been merged and released, yay!

==== PinePhone

* See also: https://linuxsmartphones.com/guest-post-in-linux-smartphones-we-trust/[In Linux Smartphones we trust]
* Martijn Braam: https://www.youtube.com/watch?v=7sxmGxuCM4g[First look at the PinePhone Keyboard dev unit]

==== PineBook Pro

* https://nullr0ute.com/2021/05/fedora-on-the-pinebook-pro/[Fedora]
* Pinebook Pro: production placed on halt due to component shortages; will keep you updated. If you want a Pinebook Pro, now is the time to pick one up.

==== LoraWAN

* link:/documentation/Pinedio/[PINE64 Pinedio]
* Partnership with RAK Wireless: link:/documentation/Pinedio/[Let's make MiRAKles happen]

==== Our Opinions On LoRaWAN

=== Custom Firmware tryout progress?

* Minicom instructions at https://bloggerbust.ca/post/how-to-configure-minicom-to-connect-over-usb-serial-uart/[bloggerbust.ca]
* https://github.com/Biktorgj/pinephone_modem_sdk/releases[Release page of Biktorgj's project]
* https://xnux.eu/devices/feature/modem-pp.html#toc-unlock-adb-access[Megi's website on Unlocking ADB access]
* Peter wanted to do a good job and thus did not finish is blog post on the topic yet, but it should be on linmob.net before the next episode lands

== Community engagement 😀
=== Listener Questions
==== Blort asked on Tilvids

_When are we going to hear/see more about the PineCube?_

Sadly no, but Ezra commits to reporting about his successes and failures in the next episode!

==== Rice Cake asked on YouTube

_Have you guys thought about verified boot camp n pinephone? 🙂_

Content to read on the topic: http://linuxgizmos.com/protecting-linux-devices-with-verified-boot-from-rom-to-userspace/[Protecting Linux devices with verified boot, from ROM to Userspace].

If you have experimented with this on the PinePhone, please get in touch!

==== iNTRa asked on YouTube

_Do either of you have your own channels that you post on?_

Ezra writes on https://elatronion.com/[Elatronion.com], and publishes videos on https://odysee.com/@Elatronion:a[Odysee] or https://www.youtube.com/channel/UCLN0SPhQo4jAPpTFNsxUnMg[YouTube].

Peter writes on https://linmob.net/[linmob.net] and publishes Video https://odysee.com/@linmob:3[Odysee], https://devtube.dev-wiki.de/video-channels/linmob/videos[Peertube] and https://www.youtube.com/c/LINMOBnet[YouTube].

==== Deon Denis asked on Youtube

_How about a FM radio back cover?_

Apologies for saying I-two-C, it's I-square-C. We don't really know beyond this: RTP's https://www.youtube.com/watch?v=ffEGdbXt2Qo[SDR Experiments]

Again: If you know more about this, please tell us about it!

== Feedback and Questions welcome!

*Remember:* This is a community podcast, so please leave feedback on what we should do better, get your suggestion's in and feel free to ask questions!

Use #pinetalk or tweet at us https://twitter.com/talkpine[@talkpine], toot at us https://fosstodon.org/@talkpine[@talkpine@fosstodon.org], send email to pinetalk@pine64.org and join our https://discord.gg/NNTUZhNqvN[Discord]!

Thank you to https://nerdzoom.media/[NerdZoom Media] for being our audio producers!