---
title: "S01E07: My name is 64 … PINE64"
date: 2021-04-23
draft: false
description: "In the seventh episode of PineTalk, a special treat is at the end of the episode: An interview with Danct12, creator of a the Arch Linux ARM spin off for PinePhone and PineTab. Prior to this, Ezra and Peter discuss Feedback, two aspects of the PINE64 April Community Update, and get to answer four (!) PinePhone-centric listener questions as the Beta Edition is starting to arrive in peoples hands."
aliases:
    - /podcast/007-my-name-is-64-pine64/
---

{{< podcast_player episode="s01e07">}}

In the seventh episode of PineTalk, the special treat is placed at the end of the movie episode: An interview with Danct12, creator of a the Arch Linux ARM Spin for PinePhone and PineTab. Before that, Ezra and Peter discuss Feedback, two aspects of the PINE64 April Community Update, and get two answer four (!) PinePhone centric listener questions as the Beta Edition is starting to arrive in peoples hands.

== Introduction

* The community quote of the day today is by Shakespeare "An SSL error has occurred and a secure connection to the server cannot be made." https://twitter.com/BiorentLape/status/1377502814742712321[Biorent Lape] send it in

== What have they been up to lately?

* Ezra:
** played https://oddwarg.itch.io/sulphur-nimbus-hels-elixir[Sulphur Nimbus: Hel's Elixir]
** working on his https://gamejolt.com/games/Televoid_out_of_the_loop/377460[point and click adventure game]
** checkout his projects on https://www.youtube.com/channel/UCLN0SPhQo4jAPpTFNsxUnMg[YouTube], https://elatronion.itch.io/[itch.io] and https://gamejolt.com/@Elatronion/games[Game Jolt].
* Peter:
** played with https://getzola.org/[Zola] for the relaunch of https://linmob.net/[linmob.net]
** after that he'll work on https://linmobapps.frama.io/[LINMOBapps.frama.io].
** he played with his https://fosstodon.org/@linmob/106070598603118848[PineCube]

== Topics

=== Feedback

* https://social.kaitaia.life/notice/A67f6QOLwG3OgadnCC[Just Another Kiwi Guy] Feeback
* Thanks to everybody else for chiming in!

=== (Community News) News

* PINE64: https://www.pine64.org/2021/04/15/april-update-new-developments/[April community update]
** https://linuxappsummit.org/[Linux App Summit]
** PinePhone accessories
* https://lore.kernel.org/netdev/20210413210235.489467-1-ezequiel@collabora.com/[Patches submitted to mainline Linux to support Rockchip's brand new RK3566 & RK3568 SoCs]

== Community engagement 😀
=== Listener Questions

* https://social.librem.one/@leimon[@leimon] asks: What would be your top three recommendations of which OS to run on it and why?
** PINE64 Wiki: https://wiki.pine64.org/index.php?title=PinePhone_Software_Releases[PinePhone Software Releases]

* Anonymous (who prefers to remain private) asked via email:
** Is the PinePhone convergence bar meant to be used only when the phone is fully charged and without the bar plugged into a power source? Or is it okay to plug the convergence bar into a power source when the phone is docked?

* What is the best way to back up the PinePhone Beta?
** https://github.com/dreemurrs-embedded/Jumpdrive/releases[JumpDrive]
** https://gitlab.gnome.org/World/pika-backup[Pika Backup]
** https://wiki.gnome.org/Apps/DejaDup[Deja-Dup]
*** https://source.puri.sm/Librem5/deja-dup[Mobile-friendly Purism fork]

* Follow up question, is PinePhone convergence okay for email/note taking or too much lag?

=== Interview

Before we sat down to record this, Peter talked to Danct12, creator of DanctNIX/Huong Tram Linux, an Arch Linux ARM based distribution for the PinePhone and PineTab.

* https://github.com/dreemurrs-embedded/Pine64-Arch/releases[DanctNIX Mobile]
** https://github.com/dreemurrs-embedded/Pine64-Arch/releases/tag/kern-5.3rc4[First release for PineTab]
* https://danct12.github.io/[Danct12's blog]
** https://danct12.github.io/VNC-on-PinePhone/[VNC on PinePhone (how to)]
** https://danct12.github.io/Pinebook-Pro-after-5-months/[Pinebook Pro as a daily driver (after 5 months)]

== Feedback welcome!

Remember: This is a community podcast, so please leave feedback on what we should do better, get your suggestion's in and feel free to ask questions! And get your "Community quote of the day" in!

Use #pinetalk or tweet at us https://twitter.com/talkpine[@talkpine], toot at us https://fosstodon.org/@talkpine[@talkpine@fosstodon.org], send email to pinetalk@pine64.org and join our https://discord.gg/NNTUZhNqvN[Discord]!

Thank you to https://nerdzoom.media/[NerdZoom Media] for being our audio producers!