---
title: "S01E10: Man of Many Apps"
date: 2021-06-04
draft: false
description: "In the first 2-digit episode of PineTalk, Ezra and Peter are happy to interview Martijn Braam, whom you may know of his involvement with postmarketOS, the many apps he develops or his videos and blog posts. They also present some homework and discuss community feedback and questions!"
aliases:
    - /podcast/010-man-of-many-apps/
---

{{< podcast_player episode="s01e10">}}

In the first 2-digit episode of PineTalk, Ezra and Peter are happy to interview Martijn Braam, whom you may know of his involvement with postmarketOS, the many apps he develops or his videos and blog posts.

They also present some homework and discuss community feedback and questions.

== Special Intro

See credits at the bottom of this post.

== What have we been up to lately?

* Ezra:
** I've been working a lot on my point and click adventure game.
** I also have been taking some time to learn how to draw.
** More relevantly, I played a whole bunch with my PineCube!
** Check out what Ezra does on https://elatronion.com/[Elatronion.com], https://odysee.com/@Elatronion:a[Odysee] and https://www.youtube.com/channel/UCLN0SPhQo4jAPpTFNsxUnMg[YouTube]!

* Peter:
** https://linmob.net/flashing-biktorgjs-modem-firmware/[Wrote that Modem Firmware install guide as promised, that mainly deals with avoiding Minicom],
** Moved his https://linmob.net/categories/weekly-update/[weekly updates] to Wednesday for personal reasons,
** made a https://linmob.net/videos/#glodroid[video] about GloDroid. It's mainly a little tutorial explaining how to do it.

But let's get to it now and start with the

== App of the Episode

* https://github.com/birros/web-archives[Web Archives]
* https://flathub.org/apps/details/com.github.birros.WebArchives[Flathub]

== Interview with Martijn Braam

Links about the things we talked about, in order of appearance:

Getting started with Linux

* http://www.knoppix.org/[Knoppix]
* Getting involved with postmarketOS
* Oliver Smith's blog: https://ollieparanoid.github.io/post/postmarketOS/[postmarketOS: Aiming for a 10 year life-cycle for smartphones]
* postmarketOS blog: https://postmarketos.org/blog/2017/09/03/100-days-of-postmarketos/[100 days of postmarketOS]
* Getting started with the PinePhone
* PINE64 Wiki: https://wiki.pine64.org/wiki/Project_Anakin[Project Anakin]
* PINE64 Wiki: https://wiki.pine64.org/wiki/PinePhone_v1.0_-_Dev[PinePhone v1.0 - Dev]
* Martijn Braam: https://www.youtube.com/watch?v=VyeD1sfQNoM[Putting together the PinePhone prototype]
* App Development
* https://blog.brixit.nl/apps/[Martijn's apps]
* How to help with postmarketOS development?
* https://gitlab.com/postmarketOS/pmaports/-/issues?label_name%5B%5D=device-pine64-pinephone[PinePhone issues on the postmarketOS issue tracker]
* https://wiki.postmarketos.org/wiki/Porting_to_a_new_device[postmarketOS Porting Guide]
* Upcoming PinePhone keyboard
* Wikipedia: https://en.wikipedia.org/wiki/I%C2%B2C[I²C]
* Martijn Braam: https://www.youtube.com/watch?v=7sxmGxuCM4g[First look at the PinePhone Keyboard dev unit]

Thank's again to Martijn for coming on!

Follow Martijn's work on:

* https://www.youtube.com/channel/UC4UXU2ZkeAwEFlLv1Yt1UMQ[YouTube]
* https://odysee.com/@martijn:b[LBRY/Odysee]
* https://blog.brixit.nl/[Blog]
* https://git.sr.ht/~martijnbraam/[sourcehut]
* and the http://cast.postmarketos.org/[postmarketOS podcast]!

== Community News
* PINE64: https://www.pine64.org/2021/05/19/femtostar-taking-aim-for-the-stars/[FemtoStar: taking aim for the stars]
* Megi's blog: https://xnux.eu/log/#033[PinePHone kernel news]

== Community engagement 😀
=== Homework on PineCube (Ezra)

Things Ezra did:

* Installing Armbian without a screen (sounds more impressive than it is)
** I simply downloaded the https://www.armbian.com/pinecube/[PineCube Armbian image].
** Flashed the image to an SD card.
** Plugged in the PineCube to power and ethernet and shabamalama! I was 99% done.
** An SSH server is installed by default on the image, so I simply had to find my PineCube's IP, which I did using the following command
** `+nmap -sP 192.168.1.0/24+`
** And logged in using the default values of:
** user: `+root+`
** pass: `+1234+`
* Install media-ctl && ffmpeg
** media-ctl is a part of v4l-utils and is useful for configuring the camera.
** ffmpeg is… well, ffmpeg, must I really explain?

It's what I use to take the video feed of the camera and stream it via RTMP to a RTMP server, which I setup next.

* RTMP server
** I followed a https://www.servermania.com/kb/articles/nginx-rtmp/[tutorial] to help me setup NGINX for RTMP streaming. It was simple enough once I wrapped my head around it. I never used NGINX or RTMP before, so it was quite the fun new experience. 🙂
* Personal livestream of me cooking to my friends
** After getting everything setup, I though I'd actually have some fun with it, so I streamed myself making supper to my friends! 😛
** The camera seems much better than that of the PinePhone, the reason for this is lens.
* I have a few projects in mind, I'll definitly make a video about the PineCube. And, ofc, talk about it on the PineTalk when I get around to it.
** Automation using TensorFlow Lite for object recognition. (saving the past few minutes and few future minutes locally on the device) or something like that.
** Peter had the idea of doing a livestream on YT or some other video platform using the PineCube as a camera, could be fun for any Pine related livestream I may do in the future.

=== Homework regarding FM radio (Peter)

Last episode, we could not give a good answer to the question Deon Denis asked on Youtube: How about a FM radio back cover?
So:

* How do other devices implement this?
** Headset serves as antenna
** Sometimes implemented within the SoC (e.g. MediaTek MT6753)
** Sometimes within the Wifi/BT chip (e.g. Samsung Galaxy SII)
* Do we have support for FM radio?
** the Realtek RTL 8723CS chip used for WiFi and Bluetooth in the PinePhone https://www.realtek.com/en/press-room/news-releases/item/realtek-to-show-latest-wlan-iot-solutions-at-internet-of-things-world-2015[alledgedly supports receiving FM radio] according to its announcement, but it's nowhere to be found on the http://files.pine64.org/doc/datasheet/pine64/RTL8723BS.pdf[spec sheet].
** but: We don't have a driver that would support this, and we don't have the hardware for it.
* Would the Pogopin i2c (i-squared-c bus (inter-integrated-circuit interface) offer enough bandwith for fm-radio on the PinePhone?
** bandwith is rather limited, but https://en.wikipedia.org/wiki/I%C2%B2C#Design[actual "hard numbers" information seems to be scarce]
** it's definitely enough for keyboards 😉
** (https://www.circuitbread.com/tutorials/i2c-fm-radio-part-15-microcontroller-basics-pic10f200[see here], or https://blog.brixit.nl/making-a-backcover-extension-for-the-pinephone/[thermal cameras])
** back to topic:
*** There's a tutorial for building an i2c fmradio accessory on https://www.circuitbread.com/tutorials/i2c-fm-radio-part-15-microcontroller-basics-pic10f200[circuitbread.com], but with this you would still have to figure out the audio side. Thankfully,
*** there are more also ready made products that have a headphone jack, e.g the https://wiki.seeedstudio.com/Grove-I2C_FM_Receiver/[Grove - I2C FM Receiver]
*** → Looks like it is actually possible to do this!
* Alternatives:
** PinePhone https://www.rtl-sdr.com/about-rtl-sdr/[RTL SDR] connected to USB
*** clunky (many cables)
*** likely requires external power source,
*** but: software exists, see e.g. https://github.com/rafaelferrari0/rtl_fm_player[rtl_fm_player]
** also, easy: (Bluetooth) Headphones with FM Radio are a thing

=== Listener Feedback
==== @DarkeyVilkulak on Odysee wrote:

PinePhone"LoRA is not for sending images. Kids these days are really spoiled ;D What about simple text communication and long range mesh for simple communication. It can use some kind of low bandwidth encryption. There are several projects like https://meshtastic.org/[Meshtastic] about that."

=== Listener Questions
==== Sebastian asked via email

1) combability of the frameworks/distros

PinePhonePinePhoneIs there a way (or some projects that try) to run apps, that where written with one desktops framework, to run those on another desktop? Like running Lomiri apps on kde-mobile?

* PinePhone https://gitlab.manjaro.org/manjaro-arm/packages/community/lomiri-dev[Manjaro Lomiri Dev Packages]
* https://github.com/accumulator/Quickddit[Quickddit, AUR]
* Dylan van Assche's https://gitlab.com/dylanvanassche/convergence-components[Convergence Components]
* somewhat relevant LINMOB.net https://linmob.net/pinephone-daily-driver-challenge-part4-crossing-desktop-environment-boudaries/[post about running Plasma Mobile apps on Phosh]

Additionally, when I see things right, quite some apps aren't packaged
for every (major) PinePhone distro (even though they use the same
framework). So it would be even great, to use AUR on mobian (also it
sounds somewhat strange). I just mean, it would be great, when software
for a specific need, wouldn't have to be written over and over again.

2) Different starting points

Where are good starting points (and where to
find them) that would help different parts of the ecosystem?

* There is a lot
* file bug reports (or help triangulating those)
* help with documentation
* help with metadata/other little things: If there's a project you like a lot, but it does not have a desktop file or icon, maybe help with that. Or contribute https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html[AppStream Metadata] via pull request. Pick what you think is up your alley, the worst thing that can happen is that your pull or merge request is being declined.
* helping other users: Forums, chat, …
* like Martijn said in our interview: Pick something (maybe there's a rather simple app that you lack) and get started with that. Pick a framework, pick a language, and dive in. Eventually, you might come up with something, and even if it's objectively not very good, you will have learned something, and if you keep going, you might eventually get decent at it.

== Feedback and Questions welcome!

*Remember:* This is a community podcast, so please leave feedback on what we should do better, get your suggestion's in and feel free to ask questions!

Use #pinetalk or tweet at us https://twitter.com/talkpine[@talkpine], toot at us https://fosstodon.org/@talkpine[@talkpine@fosstodon.org], send email to pinetalk@pine64.org and join our https://discord.gg/NNTUZhNqvN[Discord]!

== Credits:
=== Intro and Outro Music

Music by https://www.youtube.com/channel/UCqHurkQJbpHBG_QQh6sB2GQ[Bradley (PixelPaintbrush) Ames]

Thank you to https://nerdzoom.media/[NerdZoom Media] for being PineTalk's audio producers!

== Special Intro credits

Script & Editing: Ezra

Cast

* Ezra as himself
* Peter as Faang and his minion.

=== Audio
==== Atmosphere

Calm Forest Birds
BurghRecords - Sonny Fascia

==== Music

https://incompetech.filmmusic.io/song/5738-aquarium[Aquarium] by Kevin MacLeod, https://filmmusic.io/standard-license[License]
https://incompetech.filmmusic.io/song/4708-leaving-home[Leaving Home] by Kevin MacLeod, https://filmmusic.io/standard-license[License]
https://incompetech.filmmusic.io/song/4606-waltz-of-treachery[Waltz of Treachery] by Kevin MacLeod, https://filmmusic.io/standard-license[License]