---
title: "S01E02: New Accessories and UBports with Dalton Durst"
date: 2021-02-12
draft: false
description: "In the second episode of the PineTalk Ezra and Peter talk about to Dalton Durst, Development Manager at UBports, about Ubuntu Touch in general and on the PinePhone more specifically. They also discuss the announcement of the 'End of Community Editions' and answer awesome community questions."
aliases:
    - /2021/02/12/002-new-accessories-and-ubports-with-dalton-durst/
---

{{< podcast_player episode="s01e02">}}

In the second episode of the PineTalk Ezra and Peter talk about to Dalton Durst, Development Manager at UBports, about Ubuntu Touch in general and on the PinePhone more specifically. They also discuss the announcment of the 'End of Community Editions' and answer awesome community questions.

== What have we been up to lately?

* Ezra:
** Elatronion: https://www.youtube.com/channel/UCLN0SPhQo4jAPpTFNsxUnMg[YouTube], https://odysee.com/@Elatronion:a[Odysee]
** Usergames (https://www.youtube.com/channel/UCcmmCXke5sTLT7U29_P9GQw[YouTube])
* Peter:
** LINMOBapps: https://linmobapps.frama.io
** Peter’s blog: https://linmob.net

== Topics

=== Interview with Dalton Durst (Development manager at UBports)

* https://daltondur.st/[Dalton Durst] is the Development Manager of the https://ubports.com/[UBports project], which picked up https://ubuntu-touch.io/[Ubuntu Touch] when Canonical decided to discontinue it.
* Context: https://ubuntu.com/blog/growing-ubuntu-for-cloud-and-iot-rather-than-phone-and-convergence[Canonicals announcement to discontinue Unity 8 development (and thus Ubuntu for Devices/Ubuntu Touch)]
* PinePhone Prototypes and related hardware:
** https://wiki.pine64.org/index.php?title=Project_Anakin[Project Anakin]
** https://wiki.pine64.org/wiki/Project_Don%27t_be_evil[Project Don’t be evil]
** https://pine64.com/product/pine64-air-mouse-with-keyboard/?v=0446c16e2e66[Airmouse]
* How to help:
** Translations: https://docs.ubports.com/en/latest/
** Contribution Section: https://docs.ubports.com/en/latest/contribute/index.html
* How can people get in touch:
** https://t.me/utonpine[@UTonPine Telegram]
** See also "Get help" section on the https://devices.ubuntu-touch.io/device/pinephone/[PinePhone device page]

=== PINE64 Community News

* PINE64: https://www.pine64.org/2021/02/02/the-end-of-community-editions/[The End of Community Editions]
* LinuxSmartphones: https://linuxsmartphones.com/hackers-develop-open-source-firmware-for-the-pinephone-modem-use-it-to-make-phone-calls/[PinePhone Modem Firmware news]

=== New Products (if any)

* https://pine64.com/product/pinephone-flex-break-out-board/?v=0446c16e2e66[PINEPHONE FLEX BREAK-OUT BOARD]
* https://pine64.com/product/pinephone-microsd-extender/?v=0446c16e2e66[PINEPHONE microSD EXTENDER ]

=== Your feedback and questions

Due to time contraints, we could only tackle a few of your questions - please keep them coming. We might answer your question in the next episode!

* Orli on the future of Linux Phones
* Odineee: On the impact of NVidia's purchase of ARM on PINE64 and about future Risc-V products

The Podcast is in progress of being listed in all the directories you suggested - unfortunately it's really hard to get that done with some directories, which is why we can't report full success yet.

This episode also features chapter markers, a feature that allows you to skip topics you are not that interested in.

Remember: This is a community podcast, so please leave feedback on what we should do better, get your suggestion's in and feel free to ask questions!

You can join the Discord channel https://discord.gg/NNTUZhNqvN["Pinetalk-Podcast" on PINE64's discord], you can send us an email at pinetalk@pine64.org and tweet at us, we're https://twitter.com/talkpine[@talkpine].

Thank you to NerdZoom Media for being our audio producers!