---
title: "S01E12: Privacy and Security with RTP"
date: 2021-07-04
draft: false
description: "In the twelfth episode Ezra and Peter discuss some Community news and interview content creator RTP, who is all about privacy and security. They also discuss (your) community feedback and questions!"
aliases:
    - /podcast/012-privacy-and-security-with-rtp/
---

{{< podcast_player episode="s01e12">}}

In the twelfth episode of PineTalk, Ezra and Peter are joined by RTP to talk privacy and security. They also discuss community news: Pineroot, InfiniTime 1.2.0, accelerated video playback on PinePhone and an example for a Lora communicator. The episode concludes with feedback regarding Signal Desktop on PinePhone and two hardware-centric questions.

== What have we been up to lately?

* Ezra:
** https://www.youtube.com/channel/UCLN0SPhQo4jAPpTFNsxUnMg[YouTube],
** https://odysee.com/@Elatronion:a[Odysee]
** https://elatronion.com/[Elatronion.com]
** Fan game: https://gamejolt.com/games/Televoid_out_of_the_loop/377460[Televoid: Out Of The Loop].
** https://www.youtube.com/playlist?list=PL290QH8A1p-SdZ54seS-LG_4G0AyDoXzG[Televoid series on YouTube]
* Peter:
** Blog post on https://linmob.net/gnu-linux-on-tablets-hardware/[GNU/Linux on Tablets]
** https://linmobapps.frama.io/[App List]

== App of the Episode

* https://apps.kde.org/itinerary/[KDE Itinerary]

== Interview with RTP

Right to Privacy is a content creator that focuses on privacy and security topics.

* The one video listeners really should watch:
* Securing SSH On Pinephone + Hydra Demo On Default Setup (Plus Fixes!) on
** https://www.youtube.com/watch?v=GAvGKlvKouY[YouTube],
** https://odysee.com/@RTP:9/securing-ssh-on-pinephone-+-hydra-demo:0[Odysee],
** https://tube.tchncs.de/videos/watch/87c5fae0-420d-4673-8dd6-81799328e70b[PeerTube].
* And here is where you can to follow RTPs work:
* https://politictech.wordpress.com/[Blog],
* https://www.youtube.com/channel/UChVCEXzi39_YEpUQhqmEFrQ[YouTube],
* https://odysee.com/$/invite/@RTP:9[Odysee],
* https://tube.tchncs.de/video-channels/privacy__tech_tips[PeerTube],
* https://fosstodon.org/@RTP[Fosstodon],
* https://twitter.com/TvPrivacy[Twitter].

Thanks again to RTP for coming on!

== Community News

=== pineroot
See https://github.com/e59e4835/pineroot[pineroot]

* is a https://buildroot.org/[buildroot] environment for PinePhone.
* https://github.com/e59e4835/pinerouter-ui[PineRouter] (see also https://twitter.com/pineroot1/status/1406068442160111620[Twitter]) which turns your PinePhone into an LTE Router appliance.
* Follow the project on https://twitter.com/pineroot1/[Twitter]

=== Brian Daniels: Hardware Accelerated Video Decoding on the PinePhone
http://briandaniels.me/2021/06/27/hardware-accelerated-video-playback-on-the-pinephone.html[Brian Daniels: Hardware Accelerated Video Decoding on the PinePhone]

=== InfiniTime 
https://github.com/JF002/InfiniTime/releases/tag/1.2.0[InfiniTime 1.2.0]

=== Lora
* Lora communication: https://hackaday.com/2021/06/26/lora-messenger-in-nokias-shell[LORA Messenger in Nokia's shell]
* https://github.com/TrevorAttema/OTGMessenger[GitHub Project]

== Community engagement 😀

=== Listener Feedback

undev wrote in about Signal Desktop Builder

* https://gitlab.com/undef1/signal-desktop-builder[Signal Desktop Builder]

=== Listener Questions

New Questions

https://mastodon.social/@jokeyrhyme/106458129189958787[@jokeyrhyme@mastodon.social] asked about Future revisions of PinePhone and PineBook/PineBook Pro.

https://fosstodon.org/@goldfinch/106485041245896224[@goldfinch@fosstodon.org] asked about the hardware we would like to see from PINE64 in the future

Modular hardware

* https://www.mntmn.com/[Mntmn]
* https://www.crowdsupply.com/eoma68/micro-desktop[EOMA68]

Feedback and Questions welcome!

*Remember:* This is a community podcast, so please leave feedback on what we should do better, get your suggestion's in and feel free to ask questions!

Use #pinetalk or tweet at us https://twitter.com/talkpine[@talkpine], toot at us https://fosstodon.org/@talkpine[@talkpine@fosstodon.org], send email to pinetalk@pine64.org and join our https://discord.gg/NNTUZhNqvN[Discord]!

== Credits
=== Intro and Outro Music

Music by https://www.youtube.com/channel/UCqHurkQJbpHBG_QQh6sB2GQ[Bradley (PixelPaintbrush) Ames]

Thank you to https://nerdzoom.media/[NerdZoom Media] for being PineTalk's audio producers!