---
title: "Flashing"
draft: false
menu:
  docs:
    title:
    parent: "Ox64/Software"
    identifier: "Ox64/Software/Flashing"
    weight: 3
---

This page explains how to flash an Ox64 board and a microSD card to boot the system.

== Prepare the environment
You need a Linux machine, a Raspberry Pi Pico to act as a UART adapter, the Ox64 board, and a microSD card.

Start a terminal session and set the working directory to download some files.

 cd ~/Downloads
 mkdir ox64 ox64/pico
 cd ~/Downloads/ox64/pico
 wget https://github.com/Kris-Sekula/Pine64_Ox64_SBC/blob/main/uart/picoprobe.uf2

 cd ~/Downloads/ox64
 mkdir ox64/devcube
 cd ~/Downloads/ox64/devcube
 wget https://dev.bouffalolab.com/media/upload/download/BouffaloLabDevCube-v1.8.3.zip
 sha256sum BouffaloLabDevCube-v1.8.3.zip
 unzip BouffaloLabDevCube-v1.8.3.zip
 chmod u+x BLDevCube-ubuntu

 cd ~/Downloads/ox64
 mkdir openbouffalo
 cd ~/Downloads/ox64/openbouffalo
 wget https://github.com/openbouffalo/buildroot_bouffalo/releases/download/v1.0.1/bl808-linux-pine64_ox64_full_defconfig.tar.gz
 tar -xvzf bl808-linux-pine64_ox64_full_defconfig.tar.gz

You'll need the following files to flash the BL808 SoC (M0 core, D0 core, excluding only Low Power core) and the SD card.

 m0_lowload_bl808_m0.bin - Runs on M0 wireless core and forwards interupts to the D0 for several peripherals
 d0_lowload_bl808_d0.bin - Runs on D0 multimedia core and pre-loads opensbi, the kernel and uboot dts files into ram
 bl808-firmware.bin - Runs on D0 multimedia core and contains opensbi, uboot dtb files
 sdcard.img - Runs on SD card and contain the rootfs

One option is to combine m0/d0:lowload and bl808-firmware.bin toghether. See below...

== Establish serial communication from PC to Ox64 using Pi Pico

Open a terminal and check the connected USB serial devices.

 ls /dev/ttyACM*

Set the Raspberry Pi Pico board into programming mode.

* Press the BootSel button
* Apply power by plugging the USB cable to PC
* Release the BootSel button

''Note: you could also ground pin28 to TP6 while powering.''

Copy `picoprobe.uf2` file into the new device `/media/<user>/RPI-RP2`

 cp ~/Downloads/ox64/pico/picoprobe.uf2 /media/<user>/RPI-RP2

After flashing, the device will auto-set in serial UART communication mode according to the following wiring diagram.

 OX64                      PI PICO
 uart0_Tx_GPIO14_pin1 <->  uart0_Rx_pin17
 uart0_Rx_GPIO15_pin2 <->  uart0_Tx_pin16
 Rxd_GPIO17_pin31     <->  uart1_Tx_pin6
 Txd_GPIO16_pin32     <->  uart1_Rx_pin7 
 gnd_pin38            <->  gnd_pin38/3    
 vbus5v_pin40         <->  vbus5v_pin40

== Flashing the Ox64

There are two new ports to choose from, `/dev/ttyACM0` for serial console and `/dev/ttyACM1` for DevCube flashing.

 minicom -b 2000000 -D /dev/ttyACM0

Set the Ox64 board into programming mode.

* Press the BOOT button
* Apply power or re-plug the USB cable
* Release the BOOT button

Close `minicom`. 

=== BLdevCube flashing method

Open a new terminal window to run the DevCube flasher.

 cd ~/Downloads/ox64/devcube
 ./BLDevCube-ubuntu

Select chip [BL808], press Finish and set for EACH tabs [MCU] and [IOT]. When you switch between tabs double check these common setting.

 Interface: UART
 Port/SN: /dev/ttyACM1 (make sure you don't use /dev/ttyACM0, it's used by the minicom console)
 Uart rate 2000000 (set a lower rate to avoid errors, i.e. 230400)
 UART TX is physical pin 1/GPIO 14.
 UART RX is physical pin 2/GPIO 15.

In the [MCU] tab set also:

 M0 Group[group0], Image Address [0x58000000], [PATH to m0_lowload_bl808_m0.bin]
 D0 Group[group0], Image Address [0x58100000], [PATH to d0_lowload_bl808_d0.bin]
 Click 'Create & Download' and wait until it's done

In the [IOT] tab set:

 Enable 'Single Download'
 Image Address [0x800000], [PATH to bl808-firmware.bin]
 Click 'Create & Download' again and wait until it's done
 Close DevCube

=== CLI flashing method
For those who do not want to use the DevCube, BouffaloLab provides open-source flashing packages `bflb-iot-tool` and `bflb-mcu-tool`. One option is to set up a Python virtual environment as follows. 

First, install `bflb-iot-tool` using your preferred method of managing PIP packages. 

 sudo apt install virtualenv python3-virtualenv python3.11-venv
 python3 -m venv ~/ox64_venv
 . ~/ox64_venv/bin/activate
 pip install bflb-iot-tool ''# we are *not* using bflb-mcu-tool''

NOTE: Each time you open a new terminal window you will need to re-run `. ~/ox64_venv/bin/activate` to reactivate the virtual environment.

Regarding flashing process you can combine m0/d0_lowload and bl808-firmware.bin toghether:

 cd ~/Downloads/ox64/buildroot/output/images
 dd if=/dev/zero bs=8388608 count=1 | LC_ALL=C tr "\000" "\377" > openbouffalo-bl808.bin
 dd conv=notrunc if=m0_lowload_bl808_m0.bin of=openbouffalo-bl808.bin
 dd conv=notrunc if=d0_lowload_bl808_d0.bin of=openbouffalo-bl808.bin seek=1048576 bs=1
 cat bl808-firmware.bin >> openbouffalo-bl808.bin

Next, put Ox64 in programming mode (press the BOOT button when first applying power) and flash the BL808.

 PORT=/dev/ttyACM1 ''# this will depend on which serial adapter you use''
 BAUD=115200       ''# safe value for macOS, if using Linux set to 2000000 for faster flashing''
 cd ~/Downloads/ox64/buildroot/output/images
 bflb-iot-tool --chipname bl808 --interface uart --port $PORT --baudrate $BAUD --addr 0x0 --firmware openbouffalo-bl808.bin  --single

If you get permission errors when running the commands above, you may need to add your user to the `dialout` group. Running the commands as `root` is not recommended since this will make `bflb-iot-tool` create root-owned files in your home directory.


== Flashing a microSD card

Insert microSD card into PC, locate its device file (`/dev/sdb`, for example), erase the start of the card and proceed to flashing.

 cd ~/Downloads/ox64/buildroot/output/images
 sudo dd if=/dev/zero of=/dev/sdb count=1 bs=32768 
 sudo dd if=sdcard.img of=/dev/sdb bs=1M status=progress conv=fsync

== Booting for the first time

Insert microSD card into Ox64 and set a UART connection to the Ox64 board, using the following parameters.

* UART TX is physical pin 32/GPIO 16
* UART RX is physical pin 31/GPIO 17
* Baud rate is 2000000

Choose from serial devices `/dev/ttyACM0` and `/dev/ttyACM1`, using the lower number.

 minicom -b 2000000 -D /dev/ttyACM0

Re-apply power to the Ox64 and enjoy the booting!


== Adding Nuttx RTOS

Get Nuttx image from lupyen's github page and add to the microSD card.
More info on building on https://nuttx.apache.org/docs/latest/platforms/risc-v/bl808/boards/ox64/index.html.

 cd ~/Downloads/ox64
 mkdir nuttx
 cd ~/Downloads/ox64/nuttx
 wget https://github.com/lupyuen2/wip-pinephone-nuttx/releases/download/bl808d-1/Image
 sudo mv Image ImageNuttx

Insert, mount microSD card and add image.

 sudo scp -r ~/Downloads/ox64/nuttx/ImageNUTTX <sdcardbootpoint>/ImageNuttx
 sudo scp -r ~/Downloads/ox64/nuttx/ImageNUTTX <sdcardrootfspoint>/boot/ImageNuttx

Edit /extlinux/extlinux.conf to get a new Nuttx boot option.

 cd <sdcardbootpoint>/extlinux/
 sudo chmod a=rwx extlinux.conf
 sudo cat << EOF >> extlinux.conf
  LABEL Pine64 0X64 Nuttx
         KERNEL ../ImageNuttx
         FDT ../bl808-pine64-ox64.dtb
         APPEND root=PARTLABEL=rootfs rootwait rw rootfstype=ext4 console=ttyS0,2000000 loglevel=8 earlycon=sbi
 EOF

 cd <sdcardrootfspoint>/boot/extlinux/
 sudo chmod a=rwx extlinux.conf
 sudo cat << EOF >> extlinux.conf
  LABEL Pine64 0X64 Nuttx
         KERNEL ../ImageNuttx
         FDT ../bl808-pine64-ox64.dtb
         APPEND root=PARTLABEL=rootfs rootwait rw rootfstype=ext4 console=ttyS0,2000000 loglevel=8 earlycon=sbi
 EOF
