---
title: "APN settings"
draft: false
menu:
  docs:
    title:
    parent: "PinePhone/Modem"
    identifier: "PinePhone/Modem/APN_settings"
    weight: 
---

The https://en.wikipedia.org/wiki/Access_Point_Name[APN] setting is the gateway between your carrier's cellular network and the *public Internet*. The APN setting - if not set automatically by the user's OS - has to be set by the user to enable the use of the mobile Internet on the phone.

== Setting the APN

The location of the APN setting depend on the user interface the distribution is using.

=== Gnome

One of the biggest actively maintained open (Creative Commons Public Domain) database of mobile broadband service providers and their APN settings is maintained by the Gnome project, and is available in their https://gitlab.gnome.org/GNOME/mobile-broadband-provider-info/-/blob/main/serviceproviders.xml[serviceproviders.xml]. It is a rare case, when you don't find your own provider in that list, but if it happens, then please consider contributing to it upstream. If your provider is in that database, then for setting up the APN, you only have to select your provider from the list under ` Settings > Network > Network Dropdown > Add new connection`.

Further details are https://help.gnome.org/users/gnome-help/stable/net-mobile.html.en[described by the Gnome help].

=== Phosh

APN settings are either located in `Settings > Mobile > Access Point Names` (Arch Linux ARM, PureOS, Debian + Phosh) or ` Settings > Network > Network Dropdown > Add new connection` (postmarketOS, Fedora).

=== Plasma Mobile

TBD

== List of tested carrier APN settings

A list of tested carrier APN settings can be found in the wiki under https://wiki.pine64.org/wiki/PinePhone_APN_Settings[APN settings].

