---
title: "Carrier support"
draft: false
menu:
  docs:
    title:
    parent: "PinePhone/Modem"
    identifier: "PinePhone/Modem/Carrier_support"
    weight: 
---

{{% docs/construction %}}

This page contains hints on setting up cellular network connectivity for specific carriers.
For more general information, see the carrier support section of link:/documentation/PinePhone#Modem[PinePhone]. For the APN settings see link:/documentation/PinePhone/Modem/APN_settings[APN settings].

== Check compatibility

To check if the PinePhone is supported on your carrier:

Search for your carrier on https://www.frequencycheck.com/[frequencycheck.com] and compare the carrier's LTE/GSM/WCDMA frequencies to the PinePhone's supported frequencies (listed in the https://wiki.pine64.org/wiki/File:Quectel_EG25-G_LTE_Standard_Specification_V1.3.pdf modem specification sheet).

It is likely that there will be a few frequencies that your carrier uses which are not supported by the PinePhone. Not all of the carrier's frequencies need to be supported by the PinePhone for it to work - as long as _most_ of them are supported, you will still get good coverage.

NOTE: Some providers may allow only certain known devices identified by their https://en.wikipedia.org/wiki/Type_Allocation_Code[Type Allocation Code].

== MMS workarounds

These scripts allow partial MMS support on a link:/documentation/PinePhone[PinePhone] in distributions without working MMS support:

* JMMS: https://git.sr.ht/~amindfv/jmms
* silvermms: https://gitlab.com/5ilver/silvermms
* MMS via Matrix with mmmpuppet: link:/documentation/PinePhone/Software_tricks/MMS_with_Matrix[MMS with Matrix]

There is a Haskel MMS client. MMS can also be manually composed with mmsd on the command line.