---
title: "Carrier support"
draft: false
menu:
  docs:
    title:
    parent: "PinePhone/Modem"
    identifier: "PinePhone/Modem/Carrier_support"
    weight: 
---

{{under construction}}

This page contains hints on setting up cellular network connectivity for specific carriers.
For more general information, see the carrier support section of link:/documentation/PinePhone/_index#Modem[PinePhone]. For the APN settings see link:/documentation/PinePhone/Modem/APN_settings[APN settings].

== Check compatibility

To check if the PinePhone is supported on your carrier:

Search for your carrier on https://www.frequencycheck.com/[frequencycheck.com] and compare the carrier's LTE/GSM/WCDMA frequencies to the PinePhone's supported frequencies (listed in the https://wiki.pine64.org/wiki/File:Quectel_EG25-G_LTE_Standard_Specification_V1.3.pdf modem specification sheet).

It is likely that there will be a few frequencies that your carrier uses which are not supported by the PinePhone. Not all of the carrier's frequencies need to be supported by the PinePhone for it to work - as long as _most_ of them are supported, you will still get good coverage.

== Tested and working carriers

The following is a list of carriers which has been tested by users and confirmed to be working (excerpt):

=== Asia

|===
|Country | Carrier name | SMS working | MMS working | Calls working | Data working | Tested OS (with version) and UI

| Japan | SoftBank Mobile | Not tested | Unsupported by carrier | No | No | Mobian Phosh, December 2020

| Japan | 楽天モバイル / Rakuten Mobile | Unsupported by carrier | Unsupported by carrier | Yes | Yes | Mobian Phosh, January 2021

| Japan | 楽天モバイル / Rakuten Mobile | Unsupported by carrier | Unsupported by carrier | Yes | No | Manjaro Plasma Mobile February 2021

| Japan | NTT Docomo | Yes | Not tested | Yes | Yes | Mobian Phosh, February 2021

| India | Vodafone / Vi India | Yes | Not tested | Yes | Yes | DanctNIX (Arch Linux ARM) with Phosh, March 2021

| Malaysia | Celcom | Yes | Not tested | Yes | Yes | Gentoo, SXMO

| Malaysia | Maxis | Yes | Not tested | Yes | Yes | Gentoo, SXMO

| Malaysia | U-Mobile | Yes | Not tested | Yes | Yes | Gentoo, SXMO

| Malaysia | Yes | Yes | Not tested | Yes | Yes | Gentoo, SXMO

| South Korea | KT | Yes | Not tested | Yes | Yes | Manjaro Phosh, June 2021

| China | China Mobile | Yes | Not tested | Yes | No | Mobile NixOS, December 2021

| China | China Telecom | Yes (hack needed) | Not tested | Yes (hack needed) | No | AOSC OS Phosh, January 2022

| Japan | 楽天モバイル / Rakuten Mobile | Yes | Not tested | Yes | Yes | Mobian Phosh, January 2022 (revised from January 2021)

| China | China Unicom | Yes | Not tested | Yes | Yes | https://postmarketos.org/[pmOS] 22.06.3 Phosh, [[PineModems#Bootloader_unlocking | BLunlck'd]], link:/documentation/PinePhone/_index#Firmware_update[*8M2G_30.006*], November 2022
|===

=== Africa

|===
|Country | Carrier name | SMS working | MMS working | Calls working | Data working | Tested OS (with version) and UI

| Test | Test | Yes | Yes | Yes | Yes | TestOS with Phosh, 20201129

|===

=== Europe

|===
|Country | Carrier name | SMS working | MMS working | Calls working | Data working | Tested OS (with version) and UI

| Ukraine | KyivStar | Yes | Not tested | Yes | Yes | Mobian Phosh(11Nov21)

| Ukraine | Vodafone | Yes | Not tested | Yes | Yes | Manjaro ARM Phosh(29Jun22)

| Sweden | Fello (uses Telia network) | Yes | No (data and MMS APN are different) | Yes | Yes | Mobian Phosh, October 2022

| Sweden | Hallon (uses Tre network) | Yes | Yes (when manually selecting the MMS APN) | Yes | Yes | Mobian Phosh, October 2022

| Sweden | Comviq (uses Tele2 network) | Yes | Yes (when manually selecting the MMS APN) | Yes | Yes | Mobian Phosh, October 2022

| Sweden | Tele2 | Yes | Not tested | Yes | Not tested | Manjaro ARM Posh

| Sweden | Telenor SE | Not tested | Not tested (should NOT work, data and MMS APN are different) | Yes | Not tested | Manjaro Plasma Mobile beta2

| UK     | RWG | Yes | Not tested | Yes | Yes  https://neilzone.co.uk/2022/06/rwg-mobile-apn-for-non-data-sims[(special APN)] | postmarketOS Phosh (Edge) - 11 March 2023

| UK     | Three | Yes | Not tested | Yes | Yes | Manjaro Plasma Mobile beta2

| UK     | Vodafone | Yes | Not tested | Yes | Yes | ALARM & pmOS (Phosh?), modem FW latest - 26 Feb 21

| UK     | Sky Mobile (O2) | Yes | Not tested | Yes | Yes | ArchLinux Phosh (20210908 image, fully updated) - 3 October 2021

| UK     | Smarty Mobile (Three) | Yes | Yes | Yes | Yes | Arch Linux SXMO (Wayland) - 23 March 2022

| UK     | Honest Mobile (Three) | Yes | No | Yes - buggy | Yes | postmarketOS 22.12 (Phosh) - 20 February 2023

| France     | Orange | Yes | Not tested | Yes | Yes | Manjaro Phosh Beta6 and later - 9 march 2021

| France     | SFR | Yes | Not tested | Yes | Yes | Manjaro Phosh Beta6 and later - 9 march 2021

| France     | Free | Yes | Not tested | Yes | Yes | pmOS SXMO (Wayland) - 27 March 2022

| Czech Republic     | O2 | Yes (only on 2G) | Not tested | Yes | Yes | Mobian Phosh (20210517 image up to date) - 2 June 2021

| Germany     | Congstar | Yes | Not tested | Yes | Yes (IPv4 & IPv6) | Mobian (Megi's kernel 5.13.0-rc4, apt up-to-date) with Phosh, 2021-06-07

| Germany     | E-Plus  | Yes (sending only 2G) | Not tested | Yes | Yes        | Manjaro Phosh and postmarketOS, 2021-10-15

| Germany     | Telekom  | Yes | Not tested | Yes | Not tested        | Mobian Phosh (5.10-sunxi64), 2021-07-28

| Germany     | O2 / Telefonica  | Yes | Not tested | Yes | Not tested        | Plasma Mobile

| Hungary     | Telekom  | Yes | Not tested | Yes | Yes (IPv4)        | Manjaro Phosh Beta 12, 2021-07-30

| Hungary     | Telenor/Yettel  | Yes | Not tested | Yes | Yes |  Mobian-Phosh-20210517, 2021-09-24

| Denmark     | CBB  | Yes | Not tested | Yes | Yes       | Manjaro Plasma Mobile Beta 5, 2021-06-30

| Belgium     | Telenet  | Yes | Not tested | Yes | Yes       | postmarketOS v20.05, v21.03, v21.06 and edge, 2021-08-15

| Belgium     | CARREFOUR  | Yes | Not tested | Yes | Yes       | postmarketOS v20.05, v21.03, v21.06 and edge, 2021-08-15

| Poland      | Play | Yes | Not tested | Yes | Yes | Manjaro Phosh Beta 18, 2021-11-14

| Poland      | Orange | Yes | No | Yes | Yes (IPv4 & IPv6) | Manjaro Phosh v21.10, 2021-12-23

| Poland      | Premium Mobile | Yes | No | Yes | Yes | Manjaro Phosh v22.01, 2022-01-13

| Italy       | WindTre Italy | Yes | Not tested | Yes | Yes | Archlinux ARM Plasma Mobile

| Switzerland | Salt | Yes | Not tested | Yes | Yes | Phosh on Mobian + Arch
|===

=== North America

|===
|Country | Carrier name | SMS working | MMS working | Calls working | Data working | Tested OS (with version) and UI

| USA | AT&T | Yes | Yes | Yes | Yes |
* Mobian - Phosh

| USA | T-Mobile | Yes | No | Yes | Yes |
* Arch Linux Arm 2020/11/29
* Mobian - Phosh
* Manjaro - KDE Plasma Mobile

| USA | T-Mobile | Yes | Yes | Yes | Yes |
* Mobian Bookworm (Phosh) (2022-03-08)

| USA | MetroPCS (T-Mobile) | Yes | No | Yes | Yes |
* Arch Linux Arm (Phosh,SXMO) 2021/04/29
* Manjaro - Phosh 2021/04/29
* Mobian - Phosh 2021/3/20

| USA | T-Mobile | Yes - buggy | No | Yes - buggy | Yes - buggy |
* Manjaro - Plasma Dev 2020/11/21
* Ubuntu Touch - 2020/11/26
* KDE Neon 2020/11/02

| USA | Mint Mobile (T-Mobile) | Yes | Yes | Yes | Yes |
* Mobian - Phosh 2021/3/14
* postMarketOS - Phosh, Sxmo, Plasma Mobile 2021/5/26
* Ubuntu Touch 2021/5/24
* Manjaro - Phosh 2022/3/25

| USA | Patriot Mobile (T-Mobile) | Yes | Yes | Yes | Yes |
* DanctNIX (Arch Linux ARM) - Phosh 2023/03/29

| USA | Tello (T-Mobile) | Yes | Yes | Yes | Yes |
* DanctNIX (Arch Linux ARM) - Phosh 2022-07-09

| USA | TracFone | No | No | No | No |
* postMarketOS - Phosh 2022/06/28

| USA | Verizon | Yes | Not tested | Yes | Yes |
* Mobian - Phosh 2021/3/1

| USA | US Mobile | Yes | Not tested | Yes | Not Tested |
* Mobian - Phosh 2022/01/09

| USA | Verizon | No | No | No | No |
* Ubuntu Touch 2021/5/24 (You can occasionally get the settings to work with Verizon, but it seems like the settings automatically changes the carrier to the wrong one after a few minutes)

| USA | Verizon | Not tested | Not tested | Yes | Not via gui |
* Manjaro - KDE Plasma Mobile 2021/5/10

| USA | Verizon | Yes | Not tested | Yes | Not via gui |
* Manjaro - Phosh 2021/5/31

| USA | Verizon | Yes | Not tested | Yes | Yes |
* postmarketOS - Phosh 2021/5/31

| USA | Verizon | Yes | Not tested | Yes | Yes |
* Arch - Phosh 2021/5/31

| Canada | Freedom | Yes | Not tested | Yes | Yes |
*Arch Pinephone - Phosh (APN: internet.windmobile.ca), 2021/4/25

| Canada | SpeakOut | Yes | Not tested | Yes | Not tested |
* Mobian - Phosh 2021/11/18

| USA | Consumer Cellular (AT&T) | Yes | No | Yes | Yes |
* Manjaro - Phosh 2021/06/26

| USA | Google Fi (T-Mobile) | Yes | No | Yes | Yes |
* Arch Linux Arm - Phosh 0.10.2 2021/05/29

| Mexico | Telcel | Yes | Not tested | Yes | Yes |
* Mobian - Phosh Weekly 2022/04/13
* PostmarketOS - SXMO De Sway v21.12 (stable) 2022/04/13
* PostmarketOS - Phosh v21.12 (stable) 2022/04/13
* PostmarketOS - Plasma Mobile v21.12 (stable) 2022/04/13
* PostmarketOS - sxmo edge 2021/09/09

| USA | Ting | Yes | Yes - buggy | Yes | Yes |
* Manjaro - Phosh 2021/12/10

| USA | Simple Mobile | Yes | Yes | Yes | Yes |
* Mobian - Phosh - Make sure APN is "Simple" in settings (note uppercase S)

|===

=== South America

|===
|Country | Carrier name | SMS working | MMS working | Calls working | Data working | Tested OS (with version) and UI

| Test | Test | Yes | Yes | Yes | Yes | TestOS with Phosh, 20201129

|===

=== Australia / Oceania

|===
|Country | Carrier name | SMS working | MMS working | Calls working | Data working | Tested OS (with version) and UI

| Test | Test | Yes | Yes | Yes | Yes | TestOS with Phosh, 20201129

| Australia | Beyond (Telstra) | Yes | Yes | Yes | Yes | Manjaro Phosh Beta 20.

| Australia | Belong (Telstra) | Yes | Yes | Yes | Yes | Arch (Danctnix), Feb 2022.

| Australia | Optus | Yes | No. Ticket lodged with Chatty and mmsd re multiple APN issue | Yes | Yes | Manjaro Phosh Beta 20. Manjaro Plasma Mobile Beta 9 (Data working with this release). SXMO (Danctnix and PMOS edge December 2021).

| Australia | Amaysim (Optus) | Yes | No. Ticket lodged with Chatty and mmsd re multiple APN issue | Yes | Yes | Manjaro Phosh

| Australia | OPTUS (Dodo) | | |Yes| | Manjaro Plasma Mobile 5.23.4, 2021-12.27 (deepsleep disrupts settings)

| Australia | Vodafone | Yes | Yes | Yes (No VoLTE) | Yes | pmOS Edge 5.15.3 kernel, 2022-02-10 with Phosh
|===

=== Middle East

|===
|Country | Carrier name | SMS working | USSD working | MMS working | Calls working | Data working | Tested OS (with version) and UI

| Israel| Cellcom prepay| receive+notify| NA | NA | ring+ notify | NA | on PmOS Sxmo May 14 2021.

| Israel| Cellcom Talkman| receive+notify| YES | YES (when manually selecting the MMS APN) | ring(VoLTE not working)  | YES | on mobian Feb 04, 2022, Earthquake early warning system did not show a notification on Feb 07, 2022

| Israel| Cellcom Talkman| NO | NO | NO | ring+ notify (VoLTE not working)| YES | on Plasma Mobile Feb 04, 2022

| Israel| Golan TC | receive+notify| YES | NA |  ring+ notify (VoLTE not working) | Yes | on mobian/phosh March 13 2022

| Israel| Partner prepay | receive+notify| NA |  NA | ring+ notify | NA | on PmOS Sxmo May 14 2021.

| Israel| Pelephone prepay| receive+notify| NA |  NA | ring+ notify | NA | on PmOS Sxmo May 14 2021.

| Israel| Hot prepay| receive+notify| NA | NA |  ring+ notify | NA | on PmOS Sxmo May 14 2021.

| Israel| 019 prepay| No | NA | NA |Bars only | NA | on PmOS Sxmo May 14 2021.

|===

== Special carrier notes

WARNING: This section contains providers which do not work or require special settings or actions to work.

Some carriers might support only certain frequencies or might require certain settings in Ofono or ModemManager. The following is a list of collected notes for carriers regarding special settings, hints or information:

=== USA

==== AT&T

According to https://ltefix.com/wp-content/uploads/USA-Major-Carriers-Bands-Frequencies-CA.pdf[this page], AT&T's primary bands are 12 and 17 - 700ac and 700 MHz respectively. Phone and SMS with PinePhone work out-of-the-box with AT&T. If you transfer a SIM card from another phone you were using with AT&T, you may need to activate the PinePhone through https://www.att.com/buy/wireless/byod/byod[AT&T's website]. Calls and SMS messages work. 4G and MMS work if https://www.att.com/support/article/wireless/KM1062162/[these settings] are used for APN, MMSC, and Proxy.

AT&T may drop support with their network upgrade in the near future like their child company Cricket Wireless already has. https://www.att.com/ecms/dam/att/consumer/help/pdf/Devices-Working-on-ATT-Network.pdf[This page] lists their supported devices for their new network.

==== Consumer Cellular

Consumer Cellular is a MVNO that uses both AT&T and T-Mobile networks. On the AT&T network LTE data works without special configuration. If you transfer a SIM card from another phone to the PinePhone, you may need to contact customer support in order for them to register the IMEI association to the correct hardware; in one case it was first incorrectly identified as a Samsung Google Nexus Prime before later being correctly identified by the modem model Quectel EG25-G. Customer support also explicitly enabled VoLTE on the device. After VoLTE instructions on this site were followed and APN instructions on the Consumer Cellular site were followed, VoLTE was confirmed working.

==== Cricket Wireless

Cricket wireless is a MVNO that uses AT&T's network. VoLTE was fully supported, but the PinePhone is no longer considered a compatible device in the US by the carrier (as of March 2021).

==== Faith Wireless

Faith Wireless is a MVNO that uses AT&T's network. VoLTE was fully supported, but the PinePhone comes up as a Mobile Broadband Device. Faith Wireless does not service Mobile Broadband Devices. (As of February 2022)

==== SimpleMobile

SimpleMobile is a T-Mobile prepaid MVNO operating in the United States. 4G LTE, VoLTE, data, and SMS all work on the PinePhone after activation. Activation can be done online without extra software or assistance, go to https://www.simplemobile.com/activation/byopcollectsim and make sure you have your SIM card and IMEI ready.

==== Sprint

Sprint is currently not supported due to unknown reasons. Any input regarding this issue is highly appreciated.

==== T-Mobile

According to https://ltefix.com/wp-content/uploads/USA-Major-Carriers-Bands-Frequencies-CA.pdf[this page], T-Mobile's primary frequency band for the United States is 12 (700ac MHz).

T-Mobile's bands and protocols are summarized on https://www.frequencycheck.com/carriers/t-mobile-united-states[this page].

While the PinePhone's modem does support all LTE bands that T-Mobile uses in the US (And is one of the best choices for band support with the PinePhone's modem in the US), VoLTE is still listed as "Under development" by the modem manufacturer. T-Mobile's system also does not list the PinePhone as a compatible device due to this lack of official VoLTE support. The modem is capable of working on T-Mobile with VoLTE support enabled.

==== Verizon

According to https://ltefix.com/wp-content/uploads/USA-Major-Carriers-Bands-Frequencies-CA.pdf[this page], Verizon's primary frequency band for the United States is 13 (700 MHz). Verizon's bands and protocols are summarized on https://www.frequencycheck.com/carriers/verizon-wireless-united-states[this page]. According to the same page, Verizon might restrict their network to only approved devices.

Some users reported that they were able to activate their Verizon SIM by using an Verizon-approved burner phone and then inserting the SIM into the PinePhone.

==== TracFone

Following TracFone's https://www.verizon.com/about/news/verizon-completes-tracfone-wireless-inc-acquisition[acquisition by Verizon], support for the AT&T and T-Mobile bands has been deprecated as of early June 2022. TracFone has the same issues with connecting as Verizon, as they now exclusively use Verizon's frequency band.

==== Google Fi

Only T-Mobile service works currently, not US Cellular or Sprint. The APN is `h2g2`. Information from https://forum.pine64.org/showthread.php?tid=11675&page=7[the forum].

Bear in mind that initial activation of the SIM card is not possible without an Android phone running Google Apps.

It should also be noted that Google uses a non-standard MMS implementation that is unlikely to be supported on the PinePhone at any point.

=== Europe

==== Telekom Germany

With low signal, there may be loud interference noise audible in calls on the receiving end. It has not yet been tested whether or not this problem is carrier specific. An easy fix is extending the modem antenna with aluminum foil (or similar) inside the back cover of the phone.

==== Orange Poland

Setting up dual stack IPv4 and IPv6 may require https://etherpad.gnome.org/p/dx7pbkPMCytMLMRl1eyo[extra work], because the carrier provides IPv4 connectivity on internetipv6 APN via a protocol called CLAT/NAT64.

==== Sweden

Calls, SMS, and data (2G, 3G, and 4G) should work out of the box (tested three carriers on Mobian Phosh). On about half of Swedish carriers, MMS works when set manually, the rest have different data APN and MMS APN. VoLTE (i.e. 4G calls) did not work out of the box (https://github.com/Eliot-Roxbergh/notes_pinephone[for me]) but worked well after https://github.com/the-modem-distro/pinephone_modem_sdk/blob/kirkstone/docs/FLASHING.md#adsp-versions[updating firmware] to ADSP Version 01.003.01.003 and installing https://github.com/the-modem-distro/pinephone_modem_sdk[Pinephone Modem SDK]. Regarding call quality, from my experience; 3G has the best quality, then 4G also works well although you often hear electrical white noise sound (on your side), 2G works well but there is a risk of strong noise when on bad coverage (this can affect both sides of the call). Voicemail should work, you should get a SMS when you have a missed call etc. Only issue I had was that when getting sent to voicemail in a call, for some target carriers (?) it was completely silent.

=== Asia

==== China Telecom

The baseband itself ships with bad (for CDMA, which isn't supported by EG25-G) MBN file for CT, so a force change of MBN file to the generic one is needed to get VoLTE (thus SMS+Call) work.

Run the following AT commands to force ROW_Generic_3GPP which can support VoLTE on CT:

 AT+QMBNCFG="autosel",0
 AT+QMBNCFG="select","ROW_Generic_3GPP"
 AT+QCFG="ims",1

==== SoftBank

SoftBank USIM cards are IMEI-locked, and on top of that will only work on either Android or iOS. A free SIM is available, but that one is data only. The same problem might exist with MVNO's who make use of the SoftBank network, and therefore it's advised to pick either NTT docomo or au as the MNO.

== Known issues

Known issues:

* The https://www.frequencycheck.com/models[FrequencyCheck model page] does not list either Pine64 or the PinePhone.
* T-Mobile's system does not list the PinePhone as a compatible device due to the lack of official VoLTE support from the manufacturer, despite the fact that it does work.
* MMS doesn't currently work in any distribution on the PinePhone by default. This means images and group chats will not work in text messages.
* Some providers may allow only certain known devices identified by their https://en.wikipedia.org/wiki/Type_Allocation_Code[Type Allocation Code].

== MMS workarounds

These scripts allow partial MMS support on a link:/documentation/PinePhone/_index[PinePhone] in distributions without working MMS support:

* JMMS: [https://git.sr.ht/~amindfv/jmms]
* silvermms: [https://gitlab.com/5ilver/silvermms]
* MMS via Matrix with mmmpuppet: link:/documentation/PinePhone/Software_tricks/MMS_with_Matrix[MMS with Matrix]

There is a Haskel MMS client. MMS can also be manually composed with mmsd on the command line.

== Resources

* IMEI - https://en.wikipedia.org/wiki/International_Mobile_Equipment_Identity[International Mobile Equipment Identity]

