---
title: "Installing a different operating system"
draft: false
menu:
  docs:
    title:
    parent: "PinePhone_Pro"
    identifier: "PinePhone_Pro/Installing_a_different_operating_system"
    weight: 3
---

The software releases can be installed (the process is being referred to as _flashing_) to the eMMC or to an microSD card.

== Flashing to microSD card

To install an image to the microSD card:

. Download a compatible image from link:/documentation/PinePhone_Pro/Software/Releases[Releases].
. *Important:* Typically the image will be compressed in an archive file to reduce the download size (such as _.gz_ or _.xz_). Extract the image from its archive file to get the file with the file extension _.img_.
. Write the image to your microSD card using your favorite method, examples:
* Using _dd_: On the device you're flashing the microSD card from, find the correct device under `lsblk` and then flash the image to the microSD card using `sudo dd if=*IMAGE.img* of=/dev/*[DEVICE]* bs=1M status=progress conv=fsync`. Make sure the target is the whole microSD card and not its first partition (_sdc1_ or _mmcblk0p1_ are wrong!).
* Using _bmaptool_: Make sure to select the correct device using `lsblk`. Then run bmaptool with the correct device: Download the _IMAGE.xz_ and the _IMAGE.bmap_ files, then run `bmaptool copy --bmap *IMAGE.bmap* *IMAGE.xz* /dev/*[DEVICE]*`. This takes around 2.5 minutes to flash a 4 GB file.
* Using _a graphical tool_: A graphical tool such as Gnome Disks under Linux or Etcher under Windows may also be used.
. Insert the microSD card into the top slot of the PinePhone Pro
. Boot the device using the following method:
* On the *Explorer Edition ordered after November 2023* boot the phone without any further action.
* On the *Explorer Edition ordered after July 2022* hold the _volume down key_ while booting.
* On the *Explorer Edition ordered between January and July 2022* hold the _RE_ button underneath the back cover while booting (or use the _volume down key_ if you flashed _Tow-Boot_).
* On the *Developer Edition (sold to selected developers only)* apply the bypass by shorting the testing pads while booting according to the datasheet (or use the _volume down key_ if you flashed _Tow-Boot_).

Details regarding the boot order can be found in the link:/documentation/PinePhone_Pro/Software/Boot_order/[Boot order] section.

== Flashing to the eMMC

WARNING: Since November 2023 the PinePhone Pro has ships with u-boot installed to the emmc, where it will be overwritten when flashing a new image. Many common distributions don't include a bootloader, so it is necessary to install one (such as link:/documentation/PinePhone_Pro/Software/Bootloaders/#tow-boot[Tow-Boot]) in order to get the phone to boot.

Flashing to the eMMC (the internal memory of the PinePhone Pro) can either be done using _Tow-Boot_'s USB Mass Storage mode (see link:/documentation/PinePhone_Pro/Software/Boot_order/[Boot order] if you are unsure if the device comes with Tow-Bot pre-installed) or by booting an operating system from the microSD (see the section link:/documentation/PinePhone_Pro#Flashing_to_microSD_card[Flashing to microSD card]) and by writing to the eMMC directly from there:

By using Tow-Boot:

. Power off the device
. Power on the device and hold the _volume up_ key before and during the second vibration
. The LED will turn blue if done successfully. This will only work if Tow-Boot is installed
. When connecting the device to a computer via USB it will behave like an USB drive now
. Check if the eMMC appears under `lsblk`, the output might look like the following: +
`mmcblk2      179:0    0 115.2G  0 disk` +
`├─mmcblk2p1  179:1    0   122M  0 part /boot` +
`└─mmcblk2p2  179:2    0 115.1G  0 part /` +
Note: In this example, **dev/mmcblk2** is the device, while _mmcblk2p1_ and _mmcblk2p2_ are partitions of the device. The downloaded images are images from full devices, which means that the full device (_mmcblk2_ in this example) needs to be flashed. Ignore the partitions!
. *Important:* Typically the image will be compressed in an archive file to reduce the download size (such as _.gz_ or _.xz_). Extract the image from its archive file to get the file with the file extension _.img_
. Flash the image file using `sudo dd if=*IMAGE.img* of=/dev/*DEVICE* bs=1M status=progress conv=fsync` (replace _IMAGE.img_ with the filename of the image you want to flash and make sure it has the file extension _.img_ and replace _DEVICE_ with the correct device from the _lsblk_ command)
. Reboot the PinePhone Pro

By booting a microSD card:

. Boot an operating system link:/documentation/PinePhone_Pro#Flashing_to_microSD_card[from the microSD card]. If there is already a bootloader on the eMMC installed see the section link:/documentation/PinePhone_Pro#Boot_order[Boot order] to bypass it.
. Download or copy the desired image to the microSD card as file
. Check if the eMMC appears under `lsblk`. If it doesn't appear in the output of the command, the eMMC wasn't initialized due to applying the above explained bypass method for a too long time during the boot
. *Important:* Typically the image will be compressed in an archive file to reduce the download size (such as _.gz_ or _.xz_). Extract the image from its archive file to get the file with the file extension _.img_.
. Flash the image file using `sudo dd if=*IMAGE.img* of=/dev/mmcblk2 bs=1M status=progress conv=fsync` (replace _IMAGE.img_ with the filename of the image you want to flash and make sure it has the file extension _.img_).
. Reboot the PinePhone Pro

