---
title: "Introduction"
draft: false
menu:
  docs:
    title:
    parent: "PinePhone_Pro"
    identifier: "PinePhone_Pro/Introduction"
    weight: 1
---

The PinePhone Pro is PINE64’s second smartphone and a successor to the original PinePhone. It does not, however, replace the original PinePhone. It should also not be considered a second generation PinePhone; it is a higher-end device, with much better specs, aimed at those who wish to daily-drive a open system stack. Achieving this goal will, however, take time as the software and overall smartphone software ecosystem needs to mature.

== State of the software

See the page link:/documentation/PinePhone_Pro/Various/Software_state[software state]

== Editions and revisions

Similarly to the original PinePhone, various PinePhone Pro editions are planned, the first of which is the Developer Edition (aimed at developers, as the name entails) followed by the Explorer Edition, which is aimed at early adopters.

* link:/documentation/PinePhone_Pro/Revisions/Developer_Edition[Developer Edition]
* PinePhone Pro Explorer Edition

== Help and support

Still have any questions regarding software, shipping, or ordering after reading the documentation? Please don't hesitate to contact the community in the bridged community channels for detailed answers or simply to chat with friendly people in the community! See link:/documentation[Main Page].

Please keep in mind that PINE64 is not like a regular company (see the https://www.pine64.org/philosophy/[PINE64 philosophy]) and that support resources are limited - the best way to get support quickly is to ask in the community chat! Please only contact the PINE64 support directly if questions couldn't be solved via the community chat or the documentation.