---
title: "Releases"
draft: false
menu:
  docs:
    title:
    parent: "PineTab-V/Software"
    identifier: "PineTab-V/Software/Releases"
    weight: 2
---

This page contains a list of all available releases and tools for the [[PineTab-V]] in alphabetical order. 

== Factory releases ==

The PineTab-V ships with ''Factory Test Code''. The factory test reference source code can be found here:

* https://files.pine64.org/SDK/PineTab-V/PineTab-V_factorytestcode_SDK-20230725.tar.gz[PineTab-V_factorytestcode_SDK-20230725.tar.gz] from ''pine64.org'' (8.36GB, MD5 of the TAR-GZip file: ''3e35e2760d82155b024f7601ac2b1275'')

Community releases:

* https://pine64.my-ho.st:8443/pinetabv/factoryimage/[sdcard.img] pre-built image from the community member Fishwaldo derived from the factory SDK. Note: Use ''dd'' to write it to microSD card or the eMMC.

== Linux ==

=== Gentoo

A Gentoo overlay is available https://gitlab.com/bingch/gentoo-overlay[here], it shares most ebuilds for https://wiki.gentoo.org/wiki/Embedded_Handbook/Boards/StarFive_VisionFive_2[StarFive VisionFive 2] except the kernel source ebuild contains patches from the above factory SDK.

=== KDE Plasma Yocto

A KDE Plasma Yocto Image from the community member Fishwaldo. Based on the Star64 images developed https://github.com/Fishwaldo/meta-pine64[here]. Please see this https://github.com/Fishwaldo/meta-pine64/issues/12[issue] for known problems.

==== Download

* https://github.com/Fishwaldo/meta-pine64/releases/

|===
2+| Default credentials

| Root
| `root`/`pine64`

| Default user
| `pine64`/`pine64`
|===

==== Notes
* Use ''dd'' or ''Balena Etcher'' to copy to a microSD card and then insert the microSD card into your PineTab-V and boot