---
title: "Template:Note"
draft: false
menu:
  docs:
    title:
    parent: "Templates"
    identifier: "Templates/note"
    weight: 
---

<noinclude>
{{Template}}

A note box for showing important notes.

== Usage

 IMPORTANT: note content

== Examples

 IMPORTANT: This is an note.

IMPORTANT: This is an note.

For a more flexible usage, it doesn't start with "*Note:*" by default,
you may add it manually with `*Note:*`:

 IMPORTANT: *Note:* This is an note.

IMPORTANT: *Note:* This is an note.

== Technical notes

The boxes use `display: table` to support both adaptive width and floating siblings, all other alternatives can't archive them as perfect as this solution within just one HTML element. However, it has its own flaw, if you put it into another table, its padding will gone. Avoid putting hints, notes and warnings into any tables until solution was found, or we give up and use two elements for just one box.

This template uses class `.template-box` and `.template-note`.
In the future, if the https://www.mediawiki.org/wiki/Extension:TemplateStyles[TemplateStyles Extension] is installed on this MediaWiki instance,
one may move the embedded inline styles to Template Style files.

== See also

* https://wiki.archlinux.org/title/Template:Note[ArchWiki: Template:Note]: the template on which this one is based on
* Template:Hint
* Template:Info
* Template:Warning
</noinclude><includeonly><div role="note" class="template-box template-hint" style="
display: table;
min-width: 16em;
min-height: 1.6em;
margin: .5em 0 1em;
padding: .5em 1em;
border: 1px solid #fc3;
color: #705000;
background-color: #fef6e7;
">{{{1}}}</includeonly>