---
title: "Template:Warning"
draft: false
menu:
  docs:
    title:
    parent: "Templates"
    identifier: "Templates/warning"
    weight: 
---

<noinclude>
{{Template}}

A warning box for highlighting dangerous actions and to emphasize security warnings. It starts with "*Warning:*" by default.

== Usage

 WARNING: warning content

== Example

 WARNING: This is a warning.

WARNING: This is a warning.

== Technical notes

The boxes use `display: table` to support both adaptive width and floating siblings, all other alternatives can't archive them as perfect as this solution within just one HTML element. However, it has its own flaw, if you put it into another table, its padding will gone. Avoid putting hints, notes and warnings into any tables until solution was found, or we give up and use two elements for just one box.

This template uses class `.template-box` and `.template-warning`.
In the future, if the https://www.mediawiki.org/wiki/Extension:TemplateStyles[TemplateStyles Extension] is installed on this MediaWiki instance,
one may move the embedded inline styles to Template Style files.

== See also

* https://wiki.archlinux.org/title/Template:Warning[ArchWiki: Template:Warning]: the template on which this one is based on
* Template:Hint
* Template:Info
* Template:Note
</noinclude><includeonly><div role="note" class="template-box" style="
display: table;
min-width: 16em;
min-height: 1.6em;
margin: .5em 0 1em;
padding: .5em 1em;
border: 1px solid #d33;
color: black;
background-color: #fee7e6;
"><strong>Warning:</strong> {{{1|===}}</includeonly>