---
title: "PinePhone Accessories"
draft: false
menu:
  docs:
    title:
    parent: ""
    identifier: "Phone_Accessories"
    weight: 
---

The following add-ons are available:

* link:Keyboard[Keyboard]
* link:Fingerprint_reader[Fingerprint Reader Add-on]
* link:Qi_wireless_charging[Qi Wireless Charging Add-on]
* link:LoRa[LoRa Add-on]

== Protection

The compatible cases can be found under:

* link:Cases[Cases]

The compatible screen protectors can be found under:

* link:Screen_protectors[Screen protectors]

== Stands

The following accessory is made by the community:

* https://www.thingiverse.com/thing:4654013[PinePhone Development Stand at Thingverse]

== Hubs
USB hubs do not require a custom driver and are therefore expected to be compatible with the PinePhone, as long as they are within the USB specification. On revisions the PinePhone mainboard revisions v1.1 and v1.2 the VCONN fix is required, on v1.2a and later the USB hub should work out of the box, see link:/documentation/PinePhone#Hardware_revisions[PinePhone].