---
title: "PinePhone Hardware Accessory Compatibility"
draft: false
menu:
  docs:
    title:
    parent: "Phone_Accessories"
    identifier: "Phone_Accessories/Hardware_accessory_compatibility"
    weight: 
---

The *PinePhone* and *PinePhone Pro* is compatible with a wide variety of accessories. A selection can be found here.

== Protection

=== Screen protector
The official screen protector can be found in the Pine64 store under https://pine64.com/product/pinephone-tempered-glass-screen-protector/?v=0446c16e2e66[PinePhone Tempered Glass Screen Protector].

Most screen protectors for the iPhone 11 Pro Max, iPhone XS Max and Huawei Y7 (2018) fit the PinePhone if the top notch is not obscured by a black foil or a similar obstruction.

=== Case

The Pine store has official cases:

* https://pine64.com/?product=pinephone-hard-protective-case&v=0446c16e2e66[PinePhone Hard Protective Case]
* https://pine64.com/product/pinephone-soft-tpu-protective-case[PinePhone Soft TPU Protective Case]

Tight-fit cases of other phones can't be used with the PinePhone because most times the proportions and/or camera notch won't fit. The phone can however be used with most "phone sleeves", such as those from fitBAG. The sleeve from fitBAG for the Xiaomi Redmi Note 8 Pro fits the PinePhone tightly.

The OtterBox uniVERSE Case for Samsung Galaxy XCover Pro is https://forum.pine64.org/showthread.php?tid=17580&pid=114227[reported to fit the PinePhone well] without much modification.

== Add-ons

The PinePhone and PinePhone Pro can be extended by replacing the default back cover with custom accessory connecting to the pogo pins on the phone's midsection. Currently the keyboard case, the fingerprint reader, the wireless charging case and the PineDio LoRa case is available. Details can be found under:

* link:/documentation/Phone_Accessories/_index[Accessories]
* link:/documentation/Phone_Accessories/Keyboard[Keyboard]

== Community-built accessory

The following accessory is made by the community:

* https://www.thingiverse.com/thing:4654013[PinePhone Development Stand at Thingverse]
* https://www.thingiverse.com/thing:4658870[PinePhone Hard Case by _The3DmaN_ at Thingverse]
* https://www.thingiverse.com/thing:5238124[PinePhone TPU Case by _The3DmaN_ at Thingverse]
* https://www.thingiverse.com/thing:4651177[PinePhone Hard Case by blitzaxt at Thingverse]

== Peripheral equipment

=== Hubs
USB hubs do not require a custom driver and are therefore expected to be compatible with the PinePhone, as long as they are within the USB specification. On revisions the PinePhone mainboard revisions v1.1 and v1.2 the VCONN fix is required, on v1.2a and later the USB hub should work out of the box, see link:/documentation/PinePhone/_index#Hardware revisions[PinePhone].

=== Bluetooth devices

In general, Bluetooth should be working. However, due to the audio setup on the PinePhone and PinePhone Pro being complicated due to the dynamic rerouting needed for phone calls.

<|--
|===
|Name | Product type | Bluetooth version | Result | Tested OS | Kernel version | Notes

| Beats Powerbeats Pro | Headset | TBD | Works | Ubuntu Touch | 5.6 | Working

| Sony WH-CH510 | Headset | TBD | Works | Mobian | 5.9 | Audio works with A2DP profile, when using HSP/HFP only loud noise appears, unable to make calls and talk via headphones microphone

| Sony WH-1000XM3 | Headset | TBD | Works | Manjaro | 5.11.3-1 | Audio works. Have not tested yet to make calls and talk via headphones microphone

| Sony WH-1000XM4 | Headset | TBD | Works | Manjaro | 5.14.17-1 | Audio works with A2DP profile, LDAC profile does not showup. Have not tested yet to make calls and talk via headphones microphone

| MPOW-059 | Headset | TBD | Works | Ubuntu Touch | 5.6 | Works fine most of the time, but occasionally disconnects when the phone is doing a CPU intensive task

| Apple Airpods Pro | Headset | TBD | Works | Mobian | 5.9 | Works fine, but when you are only using one ear bud and decide to use the other one, it'll disconnect and will start sending audio through the internal speaker. It also doesnt work for phone calls

|===
-->

