---
title: "Software"
draft: false
menu:
  docs:
    title:
    parent: "Ox64"
    identifier: "Ox64/Software"
    weight: 1
---

== Quick Links to the Source of OS Images Build

There is a community effort to bring updated kernels, peripherals and buildroot - Lots of communication happening in the #ox64-nutcracker channel.

* https://github.com/openbouffalo/buildroot_bouffalo[buildroot] bringing all the work below together with a bootable kernel and updated filesystem images for SD cards
* https://github.com/smaeul/u-boot/tree/bl808[U-Boot] and https://github.com/smaeul/opensbi/tree/bl808[OpenSBI] work by Smauel
* https://github.com/arm000/linux-bl808/tree/linux-next/mboxic[Kernel] IRQChip, SDCard, and (WIP) USB by arm000, Alexander Horner and others
* https://github.com/openbouffalo/OBLFR[OpenBouffalo Firmware] low_load drivers by Fishwaldo and others

Original Linux Images provided by Bouffalo - Very basic *alpha build* which are only fit for board bring up and testing purposes.

* https://github.com/bouffalolab/bl808_linux[Linux for BL808]
* https://wiki.pine64.org/wiki/File:Linux_BL808.pdf[Installation Instructions for Linux on BL808 (Chinese)]
* https://wiki.pine64.org/wiki/File:Linux_BL808_en.pdf[Installation Instructions for Linux on BL808 (English Auto-Translation)]

Toolchain:

* elf_newlib_toolchain/bin/riscv64-unknown-elf-gcc (Xuantie-900 elf newlib gcc Toolchain V2.2.5 B-20220323) 10.2.0
* linux_toolchain/bin/riscv64-unknown-linux-gnu-gcc (Xuantie-900 linux-5.10.4 glibc gcc Toolchain V2.2.4 B-20211227) 10.2.0
* cmake version 3.19.3

== Software Development Kits

* https://github.com/bouffalolab/bl_mcu_sdk[BL808 MCU SDK]
* https://dev.bouffalolab.com/download[BLDevCube Flashing Tool for Windows, macOS and Ubuntu x64]
* https://wiki.pine64.org/wiki/File:Ox64_BL808UART_connect.pdf[Ox64 UART Flashing Guide], see the https://gist.github.com/lupyuen/7a0c697b89abccda8e38b33dfe5ebaff[notes]
* https://github.com/lupyuen/lupyuen.github.io/releases/download/ox64/bl808_demo_event.bin[BL808 Demo Firmware: bl808_demo_event.bin], see the https://gist.github.com/lupyuen/7a0c697b89abccda8e38b33dfe5ebaff[notes]
* https://github.com/lupyuen/lupyuen.github.io/releases/download/ox64/whole_flash_data.bin[BL808 UART Log Firmware: whole_flash_data.bin], see the https://gist.github.com/lupyuen/7a0c697b89abccda8e38b33dfe5ebaff[notes]
* https://github.com/lupyuen/lupyuen.github.io/releases/download/ox64/BL808.DVK.Quick.Start.pdf[BL808 DVK Quick Start]
* https://github.com/bouffalolab/bl808_linux/tree/main/opensbi-0.6-808[OpenSBI for BL808]
* https://github.com/bouffalolab/bl-pac/tree/main/bl808[Rust Peripheral Access Crate (PAC) for BL808]
* https://github.com/bouffalolab/bl-pac/blob/main/bl808/bl808.svd[System View Description (SVD) for BL808]


== Build procedure

Open the terminal and create a new directory for the build:
$ cd ~/Downloads/ox64

Clone the primary Buildroot repository and the specific Buildroot Bouffalo repository:
$ git clone https://github.com/buildroot/buildroot
$ git clone https://github.com/openbouffalo/buildroot_bouffalo

Define an environment variable for the Buildroot Bouffalo overlay path:
$ export BR_BOUFFALO_OVERLAY_PATH=$(pwd)/buildroot_bouffalo

Change directory into the cloned Buildroot folder:
$ cd ~/Downloads/ox64/buildroot_bouffalo/buildroot

Apply the default configuration for Pine64 Ox64:
$ make BR2_EXTERNAL=$BR_BOUFFALO_OVERLAY_PATH pine64_ox64_defconfig
# make clean # deletes all the already compiled object files

Use the menuconfig tool to adjust the build settings:
$ make menuconfig

Within menuconfig, configure the following:

    Navigate to Target Options
    Enable Integer Multiplication and Division (M)
    Enable Atomic Instructions (A)
    Enable Single-precision Floating-point (F)
    Enable Double-precision Floating-point (D)
    Set Target ABI to lp64d
    Under Toolchain, enable Fortran support and OpenMP support

Initiate the build process, but make sure first that your PATH variable contains no spaces:
$ make

You will get the image files required for flashing in the output/images directory
