---
title: "Introduction"
draft: false
menu:
  docs:
    title:
    parent: "PineNote"
    identifier: "PineNote/Introduction"
    weight: 1
---

== State of the software

The PineNote is based on the in 2021 released Rockchip RK3566 SoC. The upstreaming status of the SoC functionality can be found on the link:/documentation/Quartz64/Development#upstreaming_status[Quartz64 development] documentation page of the Quartz64 single-board computer using the same SoC. In the link:/documentation/PineNote/Development#Kernel_modules_/_mainlining_status[PineNote development] documentation page you'll find the items specific for the PineNote.

The early adopter's batch of the PineNote is aimed solely at early adopters - more specifically, the units are solely intended to find their way into the hands of users with extensive Linux experience. If you’re looking to buy a PineNote in the first batch, you must expect to write software for it, not to write notes on it. The software shipping from the factory for the first batch will not be suitable for taking notes, reading e-books, or writing your dissertation. It may not even boot to a graphical environment.

An early version of a GNOME-based Debian image is available for link:/documentation/PineNote/Releases[testing], but should not be expected to meet general-user readiness.

== Help and support

Still have any questions regarding software, shipping, or ordering after reading the documentation? Please don't hesitate to contact the community in the bridged community channels for detailed answers or simply to chat with friendly people in the community! See link:/community/[the community page].

Please keep in mind that PINE64 is not like a regular company (see the https://www.pine64.org/philosophy/[PINE64 philosophy]) and that support resources are limited - the best way to get support quickly is to ask in the community chat. Please only contact the PINE64 support directly if questions couldn't be solved via the community chat or the documentation.